// Auto-generated by Zeus v0.1
#ifndef DOMAIN_CAPTURE_TEST_H
#define DOMAIN_CAPTURE_TEST_H

#include <stddef.h>

typedef struct {
    double* data;
    size_t dim1;
    size_t dim2;
} zeus_tensor;

void zeus_free_tensor(zeus_tensor* t);

typedef struct {
    int is_error;
    double ok_val;
    double err_val;
} zeus_result_t;

#define ZEUS_TRY(expr) ({ \
    zeus_result_t _res = (expr); \
    if (_res.is_error) return _res; \
    _res.ok_val; \
})

// Public Zeus API Boundaries
void process_secure_data();
void ai_matmul(zeus_tensor A, zeus_tensor B);

#endif // DOMAIN_CAPTURE_TEST_H
