// Auto-generated by Zeus v0.1
#ifndef TEST_SECRET_H
#define TEST_SECRET_H

#define _XOPEN_SOURCE 600
#include <stddef.h>
#include <stdint.h>
#ifdef _OPENMP
#include <omp.h>
#endif

typedef struct {
    double* data;
    size_t dim1;
    size_t dim2;
} zeus_tensor;

void zeus_free_tensor(zeus_tensor* t);

typedef struct {
    int is_error;
    double ok_val;
    double err_val;
} zeus_result_t;

#define ZEUS_TRY(expr) ({ \
    zeus_result_t _res = (expr); \
    if (_res.is_error) return _res; \
    _res.ok_val; \
})

// Zeus Security FFI Boundaries
extern void zeus_tls_handshake(void);
extern int zeus_enclave_verify_token(void);
extern void __zeus_serialize_mutation_ledger(const char* func_name);

// Zeus Native M:N Fiber Scheduler Runtime
#if defined(__unix__) || defined(__APPLE__)
#include <pthread.h>
#include <stdatomic.h>
#endif

// Task and queue structures
typedef struct zeus_task zeus_task_t;
typedef struct zeus_work_queue zeus_work_queue_t;

// Runtime API
extern void zeus_runtime_dispatch(void (*func)(void*), void* arg, int num_tasks);
extern void zeus_runtime_await(void);

// Public Zeus API Boundaries

#endif // TEST_SECRET_H
