// Auto-generated by Zeus v0.1
#define _DARWIN_C_SOURCE 1
#include "test_native_parallel.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stdatomic.h>
#include <unistd.h>

// Zeus Runtime Security FFI Stubs (Fallback Implementations)
void zeus_tls_handshake(void) {}
int zeus_enclave_verify_token(void) { return 1; }
void __zeus_serialize_mutation_ledger(const char* func_name) {}

// [ZEUS PARALLEL BLOCK #0]
typedef struct __zeus_parallel_task_0{    uint64_t start;
    uint64_t end;
    uint64_t i;
    double* sum;
} __zeus_parallel_task_0;

void __zeus_parallel_worker_0(void* __zeus_ctx) {
    __zeus_parallel_task_0* __zeus_data = (__zeus_parallel_task_0*)__zeus_ctx;
    for (uint64_t i = __zeus_data->start; i < __zeus_data->end; i++) {
        *__zeus_data->sum = (*__zeus_data->sum + i);
    }
}

// ============================================================================
// ZEUS NATIVE M:N FIBER SCHEDULER (Zero-Dependency, Lock-Free)
// ============================================================================
#if defined(__unix__) || defined(__APPLE__)
#include <pthread.h>
#include <unistd.h>
#include <stdbool.h>

typedef struct zeus_task {
    void (*func)(void*);
    void* arg;
    struct zeus_task* next;
} zeus_task_t;

typedef struct zeus_work_queue {
    zeus_task_t* head;
    zeus_task_t* tail;
    atomic_int task_count;
    pthread_mutex_t lock;
} zeus_work_queue_t;

typedef struct zeus_worker {
    pthread_t thread;
    zeus_work_queue_t queue;
    atomic_bool running;
    int worker_id;
} zeus_worker_t;

static zeus_worker_t* zeus_workers = NULL;
static int zeus_num_workers = 0;
static atomic_int zeus_total_tasks = 0;
static atomic_bool zeus_scheduler_initialized = false;

static void zeus_queue_init(zeus_work_queue_t* q) {
    q->head = NULL;
    q->tail = NULL;
    atomic_init(&q->task_count, 0);
    pthread_mutex_init(&q->lock, NULL);
}

static void zeus_queue_push(zeus_work_queue_t* q, zeus_task_t* task) {
    pthread_mutex_lock(&q->lock);
    task->next = NULL;
    if (q->tail) {
        q->tail->next = task;
    } else {
        q->head = task;
    }
    q->tail = task;
    atomic_fetch_add(&q->task_count, 1);
    pthread_mutex_unlock(&q->lock);
}

static zeus_task_t* zeus_queue_pop(zeus_work_queue_t* q) {
    pthread_mutex_lock(&q->lock);
    zeus_task_t* task = q->head;
    if (task) {
        q->head = task->next;
        if (!q->head) q->tail = NULL;
        task->next = NULL;
        atomic_fetch_sub(&q->task_count, 1);
    }
    pthread_mutex_unlock(&q->lock);
    return task;
}

static zeus_task_t* zeus_steal_task(int thief_id) {
    for (int i = 0; i < zeus_num_workers; i++) {
        if (i == thief_id) continue;
        zeus_task_t* task = zeus_queue_pop(&zeus_workers[i].queue);
        if (task) return task;
    }
    return NULL;
}

static void* zeus_worker_loop(void* arg) {
    zeus_worker_t* worker = (zeus_worker_t*)arg;
    while (atomic_load(&worker->running)) {
        zeus_task_t* task = zeus_queue_pop(&worker->queue);
        if (!task) {
            task = zeus_steal_task(worker->worker_id);
        }
        if (task) {
            task->func(task->arg);
            atomic_fetch_sub(&zeus_total_tasks, 1);
            free(task);
        } else {
            usleep(100); // Brief sleep when no work available
        }
    }
    return NULL;
}

static void zeus_scheduler_init(void) {
    if (atomic_exchange(&zeus_scheduler_initialized, true)) return;
    zeus_num_workers = sysconf(_SC_NPROCESSORS_ONLN);
    if (zeus_num_workers < 1) zeus_num_workers = 4;
    zeus_workers = calloc(zeus_num_workers, sizeof(zeus_worker_t));
    for (int i = 0; i < zeus_num_workers; i++) {
        zeus_workers[i].worker_id = i;
        atomic_init(&zeus_workers[i].running, true);
        zeus_queue_init(&zeus_workers[i].queue);
        pthread_create(&zeus_workers[i].thread, NULL, zeus_worker_loop, &zeus_workers[i]);
    }
}

static void zeus_scheduler_shutdown(void) {
    if (!atomic_load(&zeus_scheduler_initialized)) return;
    for (int i = 0; i < zeus_num_workers; i++) {
        atomic_store(&zeus_workers[i].running, false);
        pthread_join(zeus_workers[i].thread, NULL);
        pthread_mutex_destroy(&zeus_workers[i].queue.lock);
    }
    free(zeus_workers);
    atomic_store(&zeus_scheduler_initialized, false);
}

void zeus_runtime_dispatch(void (*func)(void*), void* arg, int num_tasks) {
    zeus_scheduler_init();
    atomic_fetch_add(&zeus_total_tasks, num_tasks);
    // Round-robin distribution to worker queues
    static atomic_int next_worker = 0;
    int worker_idx = atomic_fetch_add(&next_worker, 1) % zeus_num_workers;
    zeus_task_t* task = malloc(sizeof(zeus_task_t));
    task->func = func;
    task->arg = arg;
    task->next = NULL;
    zeus_queue_push(&zeus_workers[worker_idx].queue, task);
}

void zeus_runtime_await(void) {
    while (atomic_load(&zeus_total_tasks) > 0) {
        // Help with work while waiting
        zeus_task_t* task = NULL;
        for (int i = 0; i < zeus_num_workers && !task; i++) {
            task = zeus_queue_pop(&zeus_workers[i].queue);
        }
        if (!task) task = zeus_steal_task(-1);
        if (task) {
            task->func(task->arg);
            atomic_fetch_sub(&zeus_total_tasks, 1);
            free(task);
        } else {
            usleep(10);
        }
    }
}

#else
// Sequential fallback for non-POSIX systems
void zeus_runtime_dispatch(void (*func)(void*), void* arg, int num_tasks) {
    (void)num_tasks;
    func(arg);
}
void zeus_runtime_await(void) {}
#endif

// Zeus FFI Boundaries Memory Repacking Layer
void __zeus_repack_aos_to_soa(void* aos_struct_array) { }

// Zeus Static Arena Allocator (Zero-Heap Enforcer with Free-List)
#define ZEUS_ARENA_SIZE (1024 * 1024 * 64) // 64MB static pool
static uint8_t __zeus_arena[ZEUS_ARENA_SIZE];
static size_t __zeus_arena_offset = 0;

typedef struct __zeus_free_node {
    size_t size;
    struct __zeus_free_node* next;
} __zeus_free_node_t;
static __zeus_free_node_t* __zeus_free_list = NULL;

void* __zeus_arena_alloc(size_t bytes) {
    bytes = (bytes + 7) & ~7; // 8-byte align
    __zeus_free_node_t* prev = NULL;
    __zeus_free_node_t* curr = __zeus_free_list;
    while (curr) {
        if (curr->size >= bytes) {
            if (prev) prev->next = curr->next;
            else __zeus_free_list = curr->next;
            return (void*)curr;
        }
        prev = curr;
        curr = curr->next;
    }
    if (__zeus_arena_offset + bytes > ZEUS_ARENA_SIZE) {
        fprintf(stderr, "[ZEUS OOM PANIC]: Static arena capacity exceeded.\n");
        exit(1);
    }
    void* ptr = &__zeus_arena[__zeus_arena_offset];
    __zeus_arena_offset += bytes;
    return ptr;
}

void __zeus_arena_free(void* ptr, size_t bytes) {
    if (!ptr) return;
    bytes = (bytes + 7) & ~7;
    __zeus_free_node_t* node = (__zeus_free_node_t*)ptr;
    node->size = bytes;
    node->next = __zeus_free_list;
    __zeus_free_list = node;
}

void __zeus_arena_reset(void) {
    __zeus_arena_offset = 0;
    __zeus_free_list = NULL;
}

// Provide memory lifecycle tools for legacy C code to clean up our tensors
void zeus_free_tensor(zeus_tensor* t) {
    if (t && t->data) {
        size_t bytes = t->dim1 * t->dim2 * sizeof(double);
        __zeus_arena_free(t->data, bytes);
        t->data = NULL;
    }
}

void __zeus_safestate_handler() {
}

#line 1 "test_native_parallel.zs"
int main() {
    double sum = 0;
    // [ZEUS: PARALLEL BLOCK START]
    // Dispatch parallel work
    int __zeus_num_cores = 4;  // TODO: detect at runtime
    uint64_t __zeus_total = 100 - 0;
    uint64_t __zeus_chunk = (__zeus_total + __zeus_num_cores - 1) / __zeus_num_cores;
    for (int __zeus_i = 0; __zeus_i < __zeus_num_cores; __zeus_i++) {
        __zeus_parallel_task_0* __zeus_task = malloc(sizeof(__zeus_parallel_task_0));
        __zeus_task->start = 0 + __zeus_i * __zeus_chunk;
        __zeus_task->end = __zeus_task->start + __zeus_chunk;
        if (__zeus_task->end > 100) __zeus_task->end = 100;
        __zeus_task->i = 0;
        __zeus_task->sum = &sum;
        zeus_runtime_dispatch(__zeus_parallel_worker_0, __zeus_task, 1);
    }
    zeus_runtime_await();
    // [ZEUS: PARALLEL BLOCK END]
    return 0;
}

