// Auto-generated by Zeus v0.1
#ifndef TEST_VERIFY_VAR_H
#define TEST_VERIFY_VAR_H

#include <stddef.h>
#include <stdint.h>

typedef struct {
    double* data;
    size_t dim1;
    size_t dim2;
} zeus_tensor;

void zeus_free_tensor(zeus_tensor* t);

typedef struct {
    int is_error;
    double ok_val;
    double err_val;
} zeus_result_t;

#define ZEUS_TRY(expr) ({ \
    zeus_result_t _res = (expr); \
    if (_res.is_error) return _res; \
    _res.ok_val; \
})

// Zeus Security FFI Boundaries
extern void zeus_tls_handshake(void);
extern int zeus_enclave_verify_token(void);
extern void __zeus_serialize_mutation_ledger(const char* func_name);

// Public Zeus API Boundaries

#endif // TEST_VERIFY_VAR_H
