// Auto-generated by Zeus v0.1
#ifndef TEST_PARALLEL_PERF_H
#define TEST_PARALLEL_PERF_H

#define _XOPEN_SOURCE 600
#include <stddef.h>
#include <stdint.h>
#ifdef _OPENMP
#include <omp.h>
#endif

typedef struct {
    double* data;
    size_t dim1;
    size_t dim2;
} zeus_tensor;

void zeus_free_tensor(zeus_tensor* t);

typedef struct {
    int is_error;
    double ok_val;
    double err_val;
} zeus_result_t;

#define ZEUS_TRY(expr) ({ \
    zeus_result_t _res = (expr); \
    if (_res.is_error) return _res; \
    _res.ok_val; \
})

// Zeus Security FFI Boundaries
extern void zeus_tls_handshake(void);
extern int zeus_enclave_verify_token(void);
extern void __zeus_serialize_mutation_ledger(const char* func_name);

// Zeus M:N Fiber Scheduler Runtime
#if defined(__unix__) || defined(__APPLE__)
#include <ucontext.h>
#define ZEUS_MAX_FIBERS 256
#define ZEUS_FIBER_STACK_SIZE (1024 * 64)
typedef struct zeus_fiber {
    ucontext_t ctx;
    uint8_t stack[ZEUS_FIBER_STACK_SIZE];
    int state;
    void (*func)(void*);
    void* arg;
} zeus_fiber_t;
typedef struct zeus_fiber_group_t { zeus_fiber_t fibers[ZEUS_MAX_FIBERS]; int active_fibers; } zeus_fiber_group_t;
#else
typedef struct zeus_fiber_group_t { int active_fibers; } zeus_fiber_group_t;
#endif
extern zeus_fiber_group_t __zeus_fiber_group_create(void);
extern void __zeus_dummy_fiber_func(void* arg);
extern void __zeus_fiber_spawn(zeus_fiber_group_t* fg, void (*func)(void*), void* arg);
extern void __zeus_fiber_group_await(zeus_fiber_group_t* fg);

// Public Zeus API Boundaries

#endif // TEST_PARALLEL_PERF_H
