use crate::ast::{Expression, Program, Statement};
use crate::backend::{Backend, Artifact, CompileError};
use std::cell::RefCell;

pub struct CCodegen {
    pub output_name: String,
    pub struct_schemas: std::cell::RefCell<std::collections::HashMap<String, Vec<(String, crate::ast::Type)>>>,
    pub secret_vars: std::cell::RefCell<Vec<Vec<String>>>,
    pub extern_functions: std::cell::RefCell<std::collections::HashMap<String, (Vec<(String, crate::ast::Type)>, Option<crate::ast::Type>)>>,
    pub disable_adaptive: bool,
    pub export_mutation_log: bool,
}

impl CCodegen {
    pub fn new(output_name: &str) -> Self {
        CCodegen {
            output_name: output_name.to_string(),
            struct_schemas: std::cell::RefCell::new(std::collections::HashMap::new()),
            secret_vars: std::cell::RefCell::new(vec![vec![]]),
            extern_functions: std::cell::RefCell::new(std::collections::HashMap::new()),
            disable_adaptive: false,
            export_mutation_log: false,
        }
    }

    pub fn set_config(&mut self, disable_adaptive: bool, export_mutation_log: bool) {
        self.disable_adaptive = disable_adaptive;
        self.export_mutation_log = export_mutation_log;
    }

    pub fn generate_source(&self, program: &Program) -> String {
        let mut source = String::new();
        
        // Collect Struct Schemas and Extern Functions
        for stmt in &program.statements {
            if let Statement::StructDeclaration { name, fields, .. } = stmt {
                self.struct_schemas.borrow_mut().insert(name.clone(), fields.clone());
            }
            if let Statement::ExternFunctionDeclaration { name, parameters, return_type } = stmt {
                self.extern_functions.borrow_mut().insert(name.clone(), (parameters.clone(), return_type.clone()));
            }
        }
        let mut source = String::new();
        source.push_str(&format!("// Auto-generated by Zeus v0.1\n"));
        source.push_str(&format!("#include \"{}.h\"\n", self.output_name));
        source.push_str("#include <stdio.h>\n");
        source.push_str("#include <stdlib.h>\n");
        source.push_str("#include <string.h>\n\n");

        source.push_str("// Zeus Runtime Security FFI Stubs (Fallback Implementations)\n");
        source.push_str("void zeus_tls_handshake(void) {}\n");
        source.push_str("int zeus_enclave_verify_token(void) { return 1; }\n");
        source.push_str("void __zeus_serialize_mutation_ledger(const char* func_name) {}\n\n");

        // Provide memory lifecycle tools for legacy C code to clean up our tensors
        source.push_str("void zeus_free_tensor(zeus_tensor* t) {\n");
        source.push_str("    if (t && t->data) {\n");
        source.push_str("        free(t->data);\n");
        source.push_str("        t->data = NULL;\n");
        source.push_str("    }\n");
        source.push_str("}\n\n");



        if self.output_name.contains("firmware") {
            source.push_str("const char* ZEUS_CRT0 = \".global _reset\\n_reset:\\n  ldr sp, =0x20000000\\n  bl main\\n  b .\\n\";\n\n");
        }

        let mut safestate_body = None;
        for stmt in &program.statements {
            if let Statement::SafeStateBlock { statements } = stmt {
                safestate_body = Some(statements.clone());
            }
        }

        source.push_str("void __zeus_safestate_handler() {\n");
        if let Some(statements) = safestate_body {
            self.secret_vars.borrow_mut().push(Vec::new());
            for stmt in &statements {
                source.push_str(&self.generate_statement(stmt, 1));
            }
            let scope_vars = self.secret_vars.borrow_mut().pop().unwrap();
            for var in scope_vars {
                source.push_str(&format!("    memset(&{}, 0, sizeof({}));\n", var, var));
            }
        }
        source.push_str("}\n\n");

        let has_funcs = program.statements.iter().any(|s| matches!(s, Statement::FunctionDeclaration{..}));
        
        if !has_funcs {
            source.push_str("int main() {\n");
            self.secret_vars.borrow_mut().push(Vec::new());
            for stmt in &program.statements {
                source.push_str(&self.generate_statement(stmt, 1));
            }
            let scope_vars = self.secret_vars.borrow_mut().pop().unwrap();
            for var in scope_vars {
                source.push_str(&format!("    memset(&{}, 0, sizeof({}));\n", var, var));
            }
            source.push_str("    return 0;\n}\n");
        } else {
            for stmt in &program.statements {
                source.push_str(&self.generate_statement(stmt, 0));
            }
        }

        source
    }

    /// Generates the C header file (.h)
    pub fn generate_header(&self, program: &Program) -> String {
        let guard_name = format!("{}_H", self.output_name.to_uppercase());
        let mut header = String::new();
        
        header.push_str(&format!("// Auto-generated by Zeus v0.1\n"));
        header.push_str(&format!("#ifndef {}\n", guard_name));
        header.push_str(&format!("#define {}\n\n", guard_name));
        header.push_str("#include <stddef.h>\n");
        header.push_str("#include <stdint.h>\n\n");
        
        // Expose the fundamental tensor layout for legacy C apps
        header.push_str("typedef struct {\n");
        header.push_str("    double* data;\n");
        header.push_str("    size_t dim1;\n");
        header.push_str("    size_t dim2;\n");
        header.push_str("} zeus_tensor;\n\n");

        header.push_str("void zeus_free_tensor(zeus_tensor* t);\n\n");

        // Runtime Error Handling
        header.push_str("typedef struct {\n");
        header.push_str("    int is_error;\n");
        header.push_str("    double ok_val;\n");
        header.push_str("    double err_val;\n");
        header.push_str("} zeus_result_t;\n\n");

        header.push_str("#define ZEUS_TRY(expr) ({ \\\n");
        header.push_str("    zeus_result_t _res = (expr); \\\n");
        header.push_str("    if (_res.is_error) return _res; \\\n");
        header.push_str("    _res.ok_val; \\\n");
        header.push_str("})\n\n");

        // FFI Stubs for Architecture Fallbacks & Security
        header.push_str("// Zeus Security FFI Boundaries\n");
        header.push_str("extern void zeus_tls_handshake(void);\n");
        header.push_str("extern int zeus_enclave_verify_token(void);\n");
        header.push_str("extern void __zeus_serialize_mutation_ledger(const char* func_name);\n\n");

        // Traverse the AST for `pub fn` declarations and emit their C signatures
        header.push_str("// Public Zeus API Boundaries\n");
        for stmt in &program.statements {
            if let Statement::StructDeclaration { name, .. } = stmt {
                header.push_str(&format!("typedef struct {} {};\n", name, name));
            }
        }
        
        for stmt in &program.statements {
            if let Statement::FunctionDeclaration { is_pub, name, parameters, return_type, attributes, .. } = stmt {
                if *is_pub && attributes.contains(&crate::ast::FunctionAttribute::FfiExport) {
                    let mut c_ret = self.type_to_c(return_type);
                    if name == "main" {
                        c_ret = "int".to_string();
                    }
                    let mut params = Vec::new();
                    for (p_name, p_type) in parameters {
                        params.push(format!("{} {}", self.type_to_c(&Some(p_type.clone())), p_name));
                    }
                    header.push_str(&format!("{} {}({});\n", c_ret, name, params.join(", ")));
                }
            }
        }
        
        header.push_str(&format!("\n#endif // {}\n", guard_name));
        header
    }

    fn type_to_c(&self, t: &Option<crate::ast::Type>) -> String {
        match t {
            Some(crate::ast::Type::F64) => "double".to_string(),
            Some(crate::ast::Type::Tensor { .. }) => "zeus_tensor".to_string(),
            Some(crate::ast::Type::Array(base, _)) => format!("{}*", self.type_to_c(&Some(*base.clone()))),
            Some(crate::ast::Type::Struct(name)) => {
                if name == "u32" { "uint32_t".to_string() }
                else if name == "usize" { "size_t".to_string() }
                else if name == "u8" { "uint8_t".to_string() }
                else { name.clone() }
            },
            Some(crate::ast::Type::Unknown(name)) => name.clone(),
            Some(crate::ast::Type::Result(_, _)) => "zeus_result_t".to_string(),
            Some(crate::ast::Type::Pointer(base)) => format!("{}*", self.type_to_c(&Some(*base.clone()))),
            None => "void".to_string(),
        }
    }

    fn generate_statement(&self, stmt: &Statement, indent: usize) -> String {
        let pad = "    ".repeat(indent);
        match stmt {
            Statement::StructDeclaration { name, fields, is_component } => {
                let mut c_struct = format!("{}typedef struct {} {{\n", pad, name);
                for (f_name, f_type) in fields {
                    if let crate::ast::Type::Array(base, size) = f_type {
                        let size_str = self.generate_expression(size);
                        c_struct.push_str(&format!("{}    {} {}[{}];\n", pad, self.type_to_c(&Some(*(base.clone()))), f_name, size_str));
                    } else {
                        c_struct.push_str(&format!("{}    {} {};\n", pad, self.type_to_c(&Some(f_type.clone())), f_name));
                    }
                }
                c_struct.push_str(&format!("{}}} {};\n", pad, name));
                
                if *is_component {
                    format!("{}// [ZEUS: NATIVE ECS ECS_BUFFER for '{}']\n{}\n", pad, name, c_struct)
                } else {
                    format!("{}// [ZEUS: Struct '{}' registered for SoA Flattening]\n{}\n", pad, name, c_struct)
                }
            }
            Statement::Let { name, is_mut: _, is_secret, value } => {
                if let Expression::IndexAccess { base, index } = value {
                    if let Expression::Identifier(element_type) = &**base {
                        if let Some(fields) = self.struct_schemas.borrow().get(element_type) {
                            let mut out = format!("{}// [ZEUS: INVISIBLE SoA TRANSFORMATION for '{}']\n", pad, name);
                            let size_c = self.generate_expression(index);
                            for (fname, _ftype) in fields {
                                out.push_str(&format!("{}double {}_{}[{}];\n", pad, name, fname, size_c));
                            }
                            return out;
                        }
                    }
                }
                
                let expr_c = self.generate_expression(value);
                if *is_secret {
                    if let Some(scope) = self.secret_vars.borrow_mut().last_mut() {
                        scope.push(name.clone());
                    }
                }
                // For simplicity, treating all variables as double for now
                format!("{}double {} = {};\n", pad, name, expr_c)
            }
            Statement::ExpressionStatement(expr) => {
                let expr_c = self.generate_expression(expr);
                // Hardcode `print` function replacement for the prototype
                if expr_c == "print" {
                    format!("{}printf(\"Execution complete.\\n\");\n", pad)
                } else {
                    format!("{}{};\n", pad, expr_c)
                }
            }
            Statement::If { condition, consequence, alternative } => {
                let mut out = format!("{}if ({}) {{\n", pad, self.generate_expression(condition));
                for s in consequence {
                    out.push_str(&self.generate_statement(s, indent + 1));
                }
                if let Some(alt) = alternative {
                    out.push_str(&format!("{}}} else {{\n", pad));
                    for s in alt {
                        out.push_str(&self.generate_statement(s, indent + 1));
                    }
                }
                out.push_str(&format!("{}}}\n", pad));
                out
            }
            Statement::ParallelBlock { iterator, start, end, statements } => {
                let start_c = self.generate_expression(start);
                let end_c = self.generate_expression(end);
                let mut out = format!("{}// [ZEUS: PARALLEL BLOCK START (OpenMP/Threads)]\n", pad);
                out.push_str(&format!("{}#pragma omp parallel for simd\n", pad));
                out.push_str(&format!("{}for (size_t {} = {}; {} < {}; {}++) {{\n", pad, iterator, start_c, iterator, end_c, iterator));
                self.secret_vars.borrow_mut().push(Vec::new());
                for s in statements {
                    out.push_str(&self.generate_statement(s, indent + 1));
                }
                let scope_vars = self.secret_vars.borrow_mut().pop().unwrap();
                for var in scope_vars {
                    out.push_str(&format!("{}    memset(&{}, 0, sizeof({}));\n", pad, var, var));
                }
                out.push_str(&format!("{}}}\n", pad));
                out.push_str(&format!("{}// [ZEUS: PARALLEL BLOCK END]\n", pad));
                out
            }
            Statement::TargetBlock { targets, statements } => {
                let target_str = targets.join(", ");
                let mut out = format!("{}// [ZEUS: TARGET SPECIFIC START: {}]\n", pad, target_str);
                self.secret_vars.borrow_mut().push(Vec::new());
                for s in statements {
                    out.push_str(&self.generate_statement(s, indent));
                }
                let scope_vars = self.secret_vars.borrow_mut().pop().unwrap();
                for var in scope_vars {
                    out.push_str(&format!("{}memset(&{}, 0, sizeof({}));\n", pad, var, var));
                }
                out.push_str(&format!("{}// [ZEUS: TARGET SPECIFIC END]\n", pad));
                out
            }
            Statement::ProofBlock { statements } => {
                let out = format!("{}// [ZEUS: COMPILE-TIME PROOF BLOCK (Elided from Runtime)]\n", pad);
                out
            }
            Statement::EnclaveBlock { statements } => {
                let mut out = format!("{}// [ZEUS: INTEL SGX / AMD SEV ENCLAVE ENTRY]\n{}#pragma zeus_enclave_enter\n{}{{ \n", pad, pad, pad);
                self.secret_vars.borrow_mut().push(Vec::new());
                for s in statements {
                    out.push_str(&self.generate_statement(s, indent + 1));
                }
                let scope_vars = self.secret_vars.borrow_mut().pop().unwrap();
                for var in scope_vars {
                    out.push_str(&format!("{}    memset(&{}, 0, sizeof({}));\n", pad, var, var));
                }
                out.push_str(&format!("{}}}\n", pad));
                out.push_str(&format!("{}#pragma zeus_enclave_exit\n{}// [ZEUS: ENCLAVE EXIT]\n", pad, pad));
                out
            }
            Statement::TestDeclaration { name, .. } => {
                // Tests are ignored during normal codegen, they are executed via `zeus test`
                format!("{}// [ZEUS: TEST BLOCK '{}' (Elided from Build)]\n", pad, name)
            }
            Statement::SafeStateBlock { .. } => {
                format!("{}// [ZEUS: SAFESTATE BLOCK (Emitted globally)]\n", pad)
            }
            Statement::Assert(expr) => {
                let expr_c = self.generate_expression(expr);
                format!("{}// [ZEUS VERIFIED: assert({})]\n", pad, expr_c)
            }
            Statement::Import(path) => {
                format!("{}// [ZEUS IMPORT: {} (Inlined AST)]\n", pad, path)
            }
            Statement::FunctionDeclaration { is_pub: _, name, parameters, return_type, body, attributes } => {
                let mut c_ret = self.type_to_c(return_type);
                if name == "main" {
                    c_ret = "int".to_string();
                }
                let mut params = Vec::new();
                for (p_name, p_type) in parameters {
                    params.push(format!("{} {}", self.type_to_c(&Some(p_type.clone())), p_name));
                }
                
                let mut out = format!("{}{} {}({}) {{\n", pad, c_ret, name, params.join(", "));
                self.secret_vars.borrow_mut().push(Vec::new());

                // Attribute codegen injection
                for attr in attributes {
                    match attr {
                        crate::ast::FunctionAttribute::Verify(expr, has_timed_out) => {
                            if *has_timed_out {
                                let expr_c = self.generate_expression(expr);
                                out.push_str(&format!("{}    if (!({})) {{\n", pad, expr_c));
                                out.push_str(&format!("{}        fprintf(stderr, \"[ZEUS PANIC]: Zeus Runtime Verification Failure at {}.zs:%%d: Constraint '%s' violated\\n\", __LINE__, \"{}\");\n", pad, self.output_name, expr_c));
                                out.push_str(&format!("{}        exit(1);\n", pad));
                                out.push_str(&format!("{}    }}\n", pad));
                            }
                        }
                        crate::ast::FunctionAttribute::Adaptive(params) => {
                            if self.disable_adaptive {
                                out.push_str(&format!("{}    // [ZEUS ADAPTIVE]: Disabled via --disable-adaptive. Running purely deterministic.\n", pad));
                            } else {
                                out.push_str(&format!("{}    // [ZEUS ADAPTIVE]: JIT Profiler active with threshold: {}\n", pad, params));
                                if self.export_mutation_log {
                                    out.push_str(&format!("{}    __zeus_serialize_mutation_ledger(\"{}\");\n", pad, name));
                                }
                            }
                        }
                        _ => {}
                    }
                }

                for s in body {
                    out.push_str(&self.generate_statement(s, indent + 1));
                }
                let scope_vars = self.secret_vars.borrow_mut().pop().unwrap();
                for var in scope_vars {
                    out.push_str(&format!("{}    memset(&{}, 0, sizeof({}));\n", pad, var, var));
                }
                if name == "main" {
                    out.push_str(&format!("{}    return 0;\n", pad));
                }
                out.push_str(&format!("{}}}\n\n", pad));
                out
            }
            Statement::ExternFunctionDeclaration { name, parameters, return_type } => {
                let c_ret = self.type_to_c(return_type);
                let mut params = Vec::new();
                for (p_name, p_type) in parameters {
                    let mut c_type = self.type_to_c(&Some(p_type.clone()));
                    if let crate::ast::Type::Struct(_) = p_type {
                        c_type = format!("{}*", c_type);
                    }
                    params.push(format!("{} {}", c_type, p_name));
                }
                format!("{}extern {} {}({});\n", pad, c_ret, name, params.join(", "))
            }
            Statement::For { iterator, start, end, body } => {
                let start_c = self.generate_expression(start);
                let end_c = self.generate_expression(end);
                let mut out = format!("{}for (int {} = {}; {} < {}; ++{}) {{\n", pad, iterator, start_c, iterator, end_c, iterator);
                self.secret_vars.borrow_mut().push(Vec::new());
                for s in body {
                    out.push_str(&self.generate_statement(s, indent + 1));
                }
                let scope_vars = self.secret_vars.borrow_mut().pop().unwrap();
                for var in scope_vars {
                    out.push_str(&format!("{}    memset(&{}, 0, sizeof({}));\n", pad, var, var));
                }
                out.push_str(&format!("{}}}\n", pad));
                out
            }
            Statement::Return(expr) => {
                let expr_c = self.generate_expression(expr);
                let mut out = String::new();
                for scope in self.secret_vars.borrow().iter().rev() {
                    for var in scope.iter() {
                        out.push_str(&format!("{}memset(&{}, 0, sizeof({}));\n", pad, var, var));
                    }
                }
                out.push_str(&format!("{}return {};\n", pad, expr_c));
                out
            }
            Statement::Panic(msg) => {
                format!("{}fprintf(stderr, \"[ZEUS PANIC (SAFE STATE HW RESET)]: %s\\n\", \"{}\");\n{}__zeus_safestate_handler();\n{}exit(1);\n", pad, msg, pad, pad)
            }
            Statement::AtomicAdd { target, amount } => {
                format!("{}__atomic_fetch_add(&{}, {}, __ATOMIC_SEQ_CST);\n", pad, target, amount)
            }
            Statement::LineDirective(line) => {
                format!("#line {} \"{}.zs\"\n", line, self.output_name)
            }
            Statement::CfgBlock { arch, statements } => {
                let mut out = format!("{}// [ZEUS HAL: arch={}]\n", pad, arch);
                self.secret_vars.borrow_mut().push(Vec::new());
                for s in statements {
                    out.push_str(&self.generate_statement(s, indent));
                }
                let scope_vars = self.secret_vars.borrow_mut().pop().unwrap();
                for var in scope_vars {
                    out.push_str(&format!("{}memset(&{}, 0, sizeof({}));\n", pad, var, var));
                }
                out
            }
            Statement::ComptimeBlock { statements } => {
                let mut out = String::new();
                out.push_str(&format!("{}// [ZEUS COMPTIME BLOCK]\n", pad));
                for stmt in statements {
                    out.push_str(&self.generate_statement(stmt, indent));
                }
                out
            }
            Statement::ClusterBlock { statements } => {
                let mut out = String::new();
                out.push_str(&format!("{}// [ZEUS CLUSTER DISTRIBUTION: RDMA INJECTED]\n", pad));
                out.push_str(&format!("{}zeus_tls_handshake();\n", pad));
                out.push_str(&format!("{}if (!zeus_enclave_verify_token()) {{\n", pad));
                out.push_str(&format!("{}    fprintf(stderr, \"[ZEUS PANIC]: Hardware violation. Invalid cryptographic capability token for RDMA enclave.\\n\");\n", pad));
                out.push_str(&format!("{}    exit(1);\n", pad));
                out.push_str(&format!("{}}}\n", pad));
                for stmt in statements {
                    out.push_str(&self.generate_statement(stmt, indent));
                }
                out
            }
        }
    }

    fn generate_expression(&self, expr: &Expression) -> String {
        match expr {
            Expression::Identifier(name) => name.clone(),
            Expression::Number(val) => val.to_string(),
            Expression::StringLiteral(s) => format!("\"{}\"", s),
            Expression::Infix { left, operator, right } => {
                let l = self.generate_expression(left);
                let r = self.generate_expression(right);
                let op = match operator.as_str() {
                    "Plus" => "+",
                    "Minus" => "-",
                    "Star" => "*",
                    "Slash" => "/",
                    "Assign" => "=",
                    "LessThan" => "<",
                    "GreaterThan" => ">",
                    "Equal" => "==",
                    "GreaterEqual" => ">=",
                    "LessEqual" => "<=",
                    "BitShiftLeft" => "<<",
                    "BitShiftRight" => ">>",
                    "BitwiseAnd" => "&",
                    "Pipe" => "|",
                    _ => operator.as_str(),
                };
                let is_bitwise = ["BitShiftLeft", "BitShiftRight", "BitwiseAnd", "Pipe"].contains(&operator.as_str());
                if is_bitwise {
                    format!("((int){} {} (int){})", l, op, r)
                } else {
                    format!("({} {} {})", l, op, r)
                }
            }
            Expression::TensorDefinition { dimensions } => {
                let mut size_expr = String::new();
                for (i, dim) in dimensions.iter().enumerate() {
                    if i > 0 { size_expr.push_str(" * "); }
                    size_expr.push_str(&self.generate_expression(dim));
                }
                format!("zeus_allocate_tensor({})", size_expr)
            }
            Expression::FunctionCall { name, arguments } => {
                let args_c: Vec<String> = arguments.iter().map(|a| self.generate_expression(a)).collect();
                if name == "println" && args_c.len() == 1 {
                    format!("printf(\"%f\\n\", {})", args_c[0])
                } else if let Some((params, ret_type)) = self.extern_functions.borrow().get(name) {
                    let mut is_soa_translation_needed = false;
                    for (_, p_type) in params.iter() {
                        if let crate::ast::Type::Struct(_) = p_type {
                            is_soa_translation_needed = true;
                        }
                    }

                    if is_soa_translation_needed {
                        let mut block = String::from("({ ");
                        let mut call_args = Vec::new();
                        let mut writes_back = Vec::new();
                        
                        for (i, (_, p_type)) in params.iter().enumerate() {
                            if let crate::ast::Type::Struct(struct_name) = p_type {
                                if let Expression::IndexAccess { base, index } = &arguments[i] {
                                    if let Expression::Identifier(arr_name) = &**base {
                                        let idx_c = self.generate_expression(index);
                                        let temp_name = format!("_zeus_tmp_{}", i);
                                        block.push_str(&format!("{} {}; ", struct_name, temp_name));
                                        
                                        if let Some(fields) = self.struct_schemas.borrow().get(struct_name) {
                                            for (f_name, _) in fields {
                                                block.push_str(&format!("{}.{} = {}_{}[{}]; ", temp_name, f_name, arr_name, f_name, idx_c));
                                                writes_back.push(format!("{}_{}[{}] = {}.{}; ", arr_name, f_name, idx_c, temp_name, f_name));
                                            }
                                        }
                                        call_args.push(format!("&{}", temp_name));
                                        continue;
                                    }
                                }
                            }
                            call_args.push(args_c[i].clone());
                        }
                        
                        let c_ret = self.type_to_c(ret_type);
                        if c_ret == "void" {
                            block.push_str(&format!("{}({}); ", name, call_args.join(", ")));
                            for wb in writes_back {
                                block.push_str(&wb);
                            }
                            block.push_str("})");
                        } else {
                            block.push_str(&format!("{} _res = {}({}); ", c_ret, name, call_args.join(", ")));
                            for wb in writes_back {
                                block.push_str(&wb);
                            }
                            block.push_str("_res; })");
                        }
                        block
                    } else {
                        format!("{}({})", name, args_c.join(", "))
                    }
                } else {
                    format!("{}({})", name, args_c.join(", "))
                }
            }
            Expression::StructInit { .. } => "0".to_string(),
            Expression::FieldAccess { base, field } => {
                if let Expression::IndexAccess { base: arr_base, index } = &**base {
                    if let Expression::Identifier(arr_name) = &**arr_base {
                        if arr_name == "particles" {
                            // Secret SoA Access
                            let idx_c = self.generate_expression(index);
                            return format!("{}_{}[{}]", arr_name, field, idx_c);
                        }
                    }
                }
                format!("{}.{}", self.generate_expression(base), field)
            }
            Expression::IndexAccess { base, index } => {
                format!("{}[{}]", self.generate_expression(base), self.generate_expression(index))
            }
            Expression::Try(expr) => {
                let inner = self.generate_expression(expr);
                format!("ZEUS_TRY({})", inner)
            }
            Expression::Comptime(_) => {
                // Handled at compile time
                "/* unresolved comptime */".to_string()
            }
        }
    }
}

// Implement the 100-Year Backend trait
impl Backend for CCodegen {
    fn compile(&self, program: &Program) -> Result<Artifact, CompileError> {
        let source_code = self.generate_source(program);
        Ok(Artifact {
            raw_data: source_code.into_bytes(),
        })
    }
}
