use crate::ast::{Expression, Program, Statement};
use crate::backend::{Backend, Artifact, CompileError};

pub struct CCodegen {
    pub output_name: String,
    pub struct_schemas: std::cell::RefCell<std::collections::HashMap<String, Vec<(String, crate::ast::Type)>>>,
    pub secret_vars: std::cell::RefCell<Vec<Vec<String>>>,
    pub extern_functions: std::cell::RefCell<std::collections::HashMap<String, (Vec<(String, crate::ast::Type)>, Option<crate::ast::Type>)>>,
    pub soa_arrays: std::cell::RefCell<std::collections::HashSet<String>>,
    pub current_var_types: std::cell::RefCell<std::collections::HashMap<String, String>>,
    pub disable_adaptive: bool,
    pub export_mutation_log: bool,
}

impl CCodegen {
    pub fn new(output_name: &str) -> Self {
        CCodegen {
            output_name: output_name.to_string(),
            struct_schemas: std::cell::RefCell::new(std::collections::HashMap::new()),
            secret_vars: std::cell::RefCell::new(vec![vec![]]),
            extern_functions: std::cell::RefCell::new(std::collections::HashMap::new()),
            soa_arrays: std::cell::RefCell::new(std::collections::HashSet::new()),
            current_var_types: std::cell::RefCell::new(std::collections::HashMap::new()),
            disable_adaptive: false,
            export_mutation_log: false,
        }
    }

    pub fn set_config(&mut self, disable_adaptive: bool, export_mutation_log: bool) {
        self.disable_adaptive = disable_adaptive;
        self.export_mutation_log = export_mutation_log;
    }

    fn generate_secure_wipe(&self, var: &str, pad: &str) -> String {
        format!("{}{{ volatile unsigned char* _p = (volatile unsigned char*)&{}; for(size_t _i = 0; _i < sizeof({}); _i++) _p[_i] = 0; __asm__ volatile(\"\" : : \"g\"(&{}) : \"memory\"); }}\n", pad, var, var, var)
    }

    pub fn generate_source(&self, program: &Program) -> String {
        self.collect_var_types(program);
        // Collect Struct Schemas and Extern Functions
        for stmt in &program.statements {
            if let Statement::StructDeclaration { name, fields, .. } = stmt {
                self.struct_schemas.borrow_mut().insert(name.clone(), fields.clone());
            }
            if let Statement::ExternFunctionDeclaration { name, parameters, return_type } = stmt {
                self.extern_functions.borrow_mut().insert(name.clone(), (parameters.clone(), return_type.clone()));
            }
        }
        let mut source = String::new();
        source.push_str("// Auto-generated by Zeus v0.1\n");
        // BUG FIX #4: Define GNU and Darwin source flags along with _XOPEN_SOURCE before system headers
        source.push_str("#ifndef _GNU_SOURCE\n#define _GNU_SOURCE 1\n#endif\n");
        source.push_str("#ifndef _DARWIN_C_SOURCE\n#define _DARWIN_C_SOURCE 1\n#endif\n");
        source.push_str("#ifndef _XOPEN_SOURCE\n#define _XOPEN_SOURCE 600\n#endif\n");
        source.push_str(&format!("#include \"{}.h\"\n", self.output_name));
        source.push_str("#include <stdio.h>\n");
        source.push_str("#include <stdlib.h>\n");
        source.push_str("#include <stdint.h>\n");
        source.push_str("#include <string.h>\n");
        source.push_str("#include <sys/mman.h>\n");
        source.push_str("#include <fcntl.h>\n");
        source.push_str("#include <unistd.h>\n\n");
        source.push_str("// Zeus Runtime Security FFI Stubs (Fallback Implementations)\n");
        source.push_str("void zeus_tls_handshake(void) {}\n");
        source.push_str("int zeus_enclave_verify_token(void) { return 1; }\n");
        source.push_str("void __zeus_serialize_mutation_ledger(const char* func_name, const char* sig) {}\n");
        source.push_str("const char* __zeus_sign_mutation(const char* func_name, const char* data) { return \"VALID_SIG\"; }\n\n");

        source.push_str("#if defined(__x86_64__) || defined(__i386__)\n");
        source.push_str("#include <x86intrin.h>\n");
        source.push_str("#elif defined(__aarch64__)\n");
        source.push_str("static inline uint64_t __rdtsc(void) {\n");
        source.push_str("    uint64_t val;\n");
        source.push_str("    asm volatile(\"mrs %0, cntvct_el0\" : \"=r\" (val));\n");
        source.push_str("    return val;\n");
        source.push_str("}\n");
        source.push_str("#else\n");
        source.push_str("static inline uint64_t __rdtsc(void) { return 0; }\n");
        source.push_str("#endif\n\n");

        source.push_str("// ============================================================================\n");
        source.push_str("// ZEUS MICRO AI: BARE-METAL QUANTIZED INFERENCE ENGINE\n");
        source.push_str("// ============================================================================\n");
        source.push_str("static const float __zeus_micro_ai_weights[4] = {0.25f, -0.5f, 0.8f, -0.1f}; // Mock .rodata weights\n");
        source.push_str("static inline float __zeus_simd_inference_mock(float input_fuel, float input_latency) {\n");
        source.push_str("    // SIMD-optimized dot product (mocked via scalar for C-backend compatibility)\n");
        source.push_str("    float score = (input_fuel * __zeus_micro_ai_weights[0]) + (input_latency * __zeus_micro_ai_weights[1]);\n");
        source.push_str("    return score;\n");
        source.push_str("}\n\n");

        source.push_str("// RDMA Infiniband Stubs\n");
        source.push_str("void ibv_post_send(void* qp, void* wr, void** bad_wr) {}\n");
        source.push_str("void ibv_post_recv(void* qp, void* wr, void** bad_wr) {}\n\n");

        // Provide memory lifecycle tools for legacy C code to clean up our tensors
        source.push_str("void zeus_free_tensor(zeus_tensor* t) {\n");
        source.push_str("    // [ZEUS ZERO-HEAP ENFORCER]: No dynamic deallocation allowed.\n");
        source.push_str("    // Tensor data is bound to the static arena pool.\n");
        source.push_str("    if (t) t->data = NULL;\n");
        source.push_str("}\n\n");

        source.push_str("// ============================================================================\n");
        source.push_str("// ZEUS NATIVE M:N FIBER SCHEDULER (Zero-Heap, Lock-Free Work-Stealing)\n");
        source.push_str("// ============================================================================\n");
        // _XOPEN_SOURCE is now emitted at the top of the file (Bug Fix #4)
        source.push_str("#if defined(__unix__) || defined(__APPLE__)\n");
        source.push_str("#pragma GCC diagnostic push\n");
        source.push_str("#pragma GCC diagnostic ignored \"-Wdeprecated-declarations\"\n");
        source.push_str("#include <ucontext.h>\n");
        source.push_str("#pragma GCC diagnostic pop\n");
        source.push_str("#include <unistd.h>\n\n");

        // --- zeus_fiber_t ---
        source.push_str("typedef struct zeus_fiber {\n");
        source.push_str("    ucontext_t ctx;\n");
        source.push_str("    char stack[65536]; // 64KB fiber stack\n");
        source.push_str("    void (*func)(void*);\n");
        source.push_str("    void* arg;\n");
        source.push_str("    volatile uint64_t last_cycle_start;\n");
        source.push_str("    volatile int is_dead;\n");
        source.push_str("} zeus_fiber_t;\n\n");

        // --- Arena allocator ---
        source.push_str("#define ZEUS_ARENA_SIZE (1024 * 1024 * 64)\n");
        source.push_str("static char* zeus_arena_heap;\n");
        source.push_str("static volatile size_t* zeus_arena_offset;\n");
        source.push_str("static zeus_fiber_t* volatile* __zeus_active_fibers;\n");
        source.push_str("static volatile size_t* __zeus_active_fibers_count;\n\n");

        source.push_str("__attribute__((constructor)) void __zeus_init_shared_memory() {\n");
        source.push_str("    zeus_arena_heap = (char*)mmap(NULL, ZEUS_ARENA_SIZE, PROT_READ | PROT_WRITE, MAP_SHARED | MAP_ANON, -1, 0);\n");
        source.push_str("    zeus_arena_offset = (size_t*)mmap(NULL, sizeof(size_t), PROT_READ | PROT_WRITE, MAP_SHARED | MAP_ANON, -1, 0);\n");
        source.push_str("    __zeus_active_fibers = (zeus_fiber_t**)mmap(NULL, sizeof(zeus_fiber_t*), PROT_READ | PROT_WRITE, MAP_SHARED | MAP_ANON, -1, 0);\n");
        source.push_str("    __zeus_active_fibers_count = (size_t*)mmap(NULL, sizeof(size_t), PROT_READ | PROT_WRITE, MAP_SHARED | MAP_ANON, -1, 0);\n");
        source.push_str("    *zeus_arena_offset = 0;\n");
        source.push_str("    *__zeus_active_fibers_count = 0;\n");
        source.push_str("    *__zeus_active_fibers = NULL;\n");
        source.push_str("}\n\n");

        source.push_str("static inline void* __zeus_arena_alloc(size_t sz) {\n");
        source.push_str("    // Ensure 8-byte alignment\n");
        source.push_str("    sz = (sz + 7) & ~7;\n");
        source.push_str("    if (*zeus_arena_offset + sz > ZEUS_ARENA_SIZE) {\n");
        source.push_str("        fprintf(stderr, \"[ZEUS PANIC]: Arena OOM - Static Memory Boundary Exceeded (Requested %zu bytes)\\n\", sz);\n");
        source.push_str("        exit(1);\n");
        source.push_str("    }\n");
        source.push_str("    size_t old_offset = __sync_fetch_and_add(zeus_arena_offset, sz);\n");
        source.push_str("    return &zeus_arena_heap[old_offset];\n");
        source.push_str("}\n\n");



        // --- Lock-Free Work-Stealing Deque (Chase-Lev) ---
        source.push_str("// ============================================================================\n");
        source.push_str("// LOCK-FREE COOPERATIVE WORK-STEALING DEQUE (Chase-Lev, C11 Atomics)\n");
        source.push_str("// ============================================================================\n");
        source.push_str("#define ZEUS_WSQ_CAPACITY 4096\n\n");

        source.push_str("typedef struct {\n");
        source.push_str("    void* tasks[ZEUS_WSQ_CAPACITY];\n");
        source.push_str("    size_t top;    // Thieves steal from top (CAS)\n");
        source.push_str("    size_t bottom; // Owner pushes/pops from bottom\n");
        source.push_str("} zeus_wsdeque_t;\n\n");

        source.push_str("static inline void zeus_wsdeque_init(zeus_wsdeque_t* q) {\n");
        source.push_str("    __atomic_store_n(&q->top, 0, __ATOMIC_RELAXED);\n");
        source.push_str("    __atomic_store_n(&q->bottom, 0, __ATOMIC_RELAXED);\n");
        source.push_str("}\n\n");

        // Push (owner only, no CAS needed for bottom)
        source.push_str("static inline void zeus_wsdeque_push(zeus_wsdeque_t* q, void* task) {\n");
        source.push_str("    size_t b = __atomic_load_n(&q->bottom, __ATOMIC_RELAXED);\n");
        source.push_str("    q->tasks[b % ZEUS_WSQ_CAPACITY] = task;\n");
        source.push_str("    __atomic_thread_fence(__ATOMIC_RELEASE);\n");
        source.push_str("    __atomic_store_n(&q->bottom, b + 1, __ATOMIC_RELAXED);\n");
        source.push_str("}\n\n");

        // Pop (owner only, needs CAS if contending with steal)
        source.push_str("static inline void* zeus_wsdeque_pop(zeus_wsdeque_t* q) {\n");
        source.push_str("    size_t b = __atomic_load_n(&q->bottom, __ATOMIC_RELAXED) - 1;\n");
        source.push_str("    __atomic_store_n(&q->bottom, b, __ATOMIC_RELAXED);\n");
        source.push_str("    __atomic_thread_fence(__ATOMIC_SEQ_CST);\n");
        source.push_str("    size_t t = __atomic_load_n(&q->top, __ATOMIC_RELAXED);\n");
        source.push_str("    if (t <= b) {\n");
        source.push_str("        void* task = q->tasks[b % ZEUS_WSQ_CAPACITY];\n");
        source.push_str("        if (t == b) {\n");
        source.push_str("            // Last element — race with steal\n");
        source.push_str("            size_t expected = t;\n");
        source.push_str("            if (!__atomic_compare_exchange_n(&q->top, &expected, t + 1, 0, __ATOMIC_SEQ_CST, __ATOMIC_RELAXED)) {\n");
        source.push_str("                task = NULL; // Lost race to thief\n");
        source.push_str("            }\n");
        source.push_str("            __atomic_store_n(&q->bottom, t + 1, __ATOMIC_RELAXED);\n");
        source.push_str("        }\n");
        source.push_str("        return task;\n");
        source.push_str("    } else {\n");
        source.push_str("        // Empty\n");
        source.push_str("        __atomic_store_n(&q->bottom, t, __ATOMIC_RELAXED);\n");
        source.push_str("        return NULL;\n");
        source.push_str("    }\n");
        source.push_str("} \n\n");

        // Steal (thieves, CAS on top)
        source.push_str("static inline void* zeus_wsdeque_steal(zeus_wsdeque_t* q) {\n");
        source.push_str("    size_t t = __atomic_load_n(&q->top, __ATOMIC_ACQUIRE);\n");
        source.push_str("    __atomic_thread_fence(__ATOMIC_SEQ_CST);\n");
        source.push_str("    size_t b = __atomic_load_n(&q->bottom, __ATOMIC_ACQUIRE);\n");
        source.push_str("    if (t < b) {\n");
        source.push_str("        void* task = q->tasks[t % ZEUS_WSQ_CAPACITY];\n");
        source.push_str("        size_t expected = t;\n");
        source.push_str("        if (!__atomic_compare_exchange_n(&q->top, &expected, t + 1, 0, __ATOMIC_SEQ_CST, __ATOMIC_RELAXED)) {\n");
        source.push_str("            return NULL; // Lost race\n");
        source.push_str("        }\n");
        source.push_str("        return task;\n");
        source.push_str("    }\n");
        source.push_str("    return NULL;\n");
        source.push_str("}\n\n");
        source.push_str("#endif\n\n");



        // Generate C struct declarations at the top so type definitions are complete
        for stmt in &program.statements {
            if let Statement::StructDeclaration { .. } = stmt {
                source.push_str(&self.generate_statement(stmt, 0));
            }
        }

        // Generate extern function signatures so parallel blocks can see them
        for stmt in &program.statements {
            if let Statement::ExternFunctionDeclaration { name, parameters, return_type } = stmt {
                let c_ret = self.type_to_c(return_type);
                let params: Vec<String> = parameters.iter().map(|(p_name, p_type)| {
                    format!("{} {}", self.type_to_c(&Some(p_type.clone())), p_name)
                }).collect();
                source.push_str(&format!("extern {} {}({});\n", c_ret, name, params.join(", ")));
            }
        }

        // Pre-pass: Generate parallel block task structs and worker functions at top level
        let parallel_defs = self.generate_parallel_definitions(program);
        source.push_str(&parallel_defs);
        
        if self.output_name.contains("firmware") {
            source.push_str("const char* ZEUS_CRT0 = \".global _reset\\n_reset:\\n  ldr sp, =0x20000000\\n  bl main\\n  b .\\n\";\n\n");
        }

        let mut safestate_body = None;
        for stmt in &program.statements {
            if let Statement::SafeStateBlock { statements } = stmt {
                safestate_body = Some(statements.clone());
            }
        }

        source.push_str("void __zeus_safestate_handler() {\n");
        if let Some(statements) = safestate_body {
            self.secret_vars.borrow_mut().push(Vec::new());
            for stmt in &statements {
                if matches!(stmt, Statement::StructDeclaration { .. }) {
                    continue;
                }
                source.push_str(&self.generate_statement(stmt, 1));
            }
            let scope_vars = self.secret_vars.borrow_mut().pop().unwrap();
            for var in scope_vars {
                source.push_str(&self.generate_secure_wipe(&var, "    "));
            }
        }
        source.push_str("}\n\n");

        let has_funcs = program.statements.iter().any(|s| matches!(s, Statement::FunctionDeclaration{..}));
        
        if !has_funcs {
            source.push_str("int main() {\n");
            source.push_str("    pid_t sentinel_pid = fork();\n");
            source.push_str("    if (sentinel_pid == 0) {\n");
            source.push_str("        while(1) {\n");
            source.push_str("            size_t count = *__zeus_active_fibers_count;\n");
            source.push_str("            if (count > 0 && *__zeus_active_fibers != NULL) {\n");
            source.push_str("                uint64_t current_time = __rdtsc();\n");
            source.push_str("                for (size_t i = 0; i < count; i++) {\n");
            source.push_str("                    zeus_fiber_t* fib = &(*__zeus_active_fibers)[i];\n");
            source.push_str("                    if (fib->is_dead) continue;\n");
            source.push_str("                    if (fib->last_cycle_start > 0 && (current_time - fib->last_cycle_start) > 50000000) {\n");
            source.push_str("                        fprintf(stderr, \"\\n[ZEUS SENTINEL] 💀 ROGUE FIBER DETECTED! Executing Phoenix Reset! (Cycles: %llu)\\n\", current_time - fib->last_cycle_start);\n");
            source.push_str("                        fib->is_dead = 1;\n");
            source.push_str("                        *zeus_arena_offset = 0;\n");
            source.push_str("                    }\n");
            source.push_str("                }\n");
            source.push_str("            }\n");
            source.push_str("            if (getppid() == 1) exit(0);\n");
            source.push_str("            usleep(100);\n");
            source.push_str("        }\n");
            source.push_str("        exit(0);\n");
            source.push_str("    }\n");
            self.secret_vars.borrow_mut().push(Vec::new());
            for stmt in &program.statements {
                if matches!(stmt, Statement::StructDeclaration { .. }) {
                    continue;
                }
                source.push_str(&self.generate_statement(stmt, 1));
            }
            let scope_vars = self.secret_vars.borrow_mut().pop().unwrap();
            for var in scope_vars {
                source.push_str(&self.generate_secure_wipe(&var, "    "));
            }
            source.push_str("    return 0;\n}\n");
        } else {
            for stmt in &program.statements {
                if matches!(stmt, Statement::StructDeclaration { .. }) {
                    continue;
                }
                source.push_str(&self.generate_statement(stmt, 0));
            }
        }

        source
    }

    /// Generates the C header file (.h)
    pub fn generate_header(&self, program: &Program) -> String {
        let guard_name = format!("{}_H", self.output_name.to_uppercase());
        let mut header = String::new();
        
        header.push_str(&format!("// Auto-generated by Zeus v0.1\n"));
        header.push_str(&format!("#ifndef {}\n", guard_name));
        header.push_str(&format!("#define {}\n\n", guard_name));
        header.push_str("#include <stddef.h>\n");
        header.push_str("#include <stdint.h>\n\n");
        
        // Expose the fundamental tensor layout for legacy C apps
        header.push_str("typedef struct {\n");
        header.push_str("    double* data;\n");
        header.push_str("    size_t dim1;\n");
        header.push_str("    size_t dim2;\n");
        header.push_str("} zeus_tensor;\n\n");

        header.push_str("void zeus_free_tensor(zeus_tensor* t);\n\n");

        // Runtime Error Handling
        header.push_str("typedef struct {\n");
        header.push_str("    int is_error;\n");
        header.push_str("    double ok_val;\n");
        header.push_str("    double err_val;\n");
        header.push_str("} zeus_result_t;\n\n");

        header.push_str("#define ZEUS_TRY(expr) ({ \\\n");
        header.push_str("    zeus_result_t _res = (expr); \\\n");
        header.push_str("    if (_res.is_error) return _res; \\\n");
        header.push_str("    _res.ok_val; \\\n");
        header.push_str("})\n\n");

        // FFI Stubs for Architecture Fallbacks & Security
        header.push_str("// Zeus Security FFI Boundaries\n");
        header.push_str("extern void zeus_tls_handshake(void);\n");
        header.push_str("extern int zeus_enclave_verify_token(void);\n");
        header.push_str("extern void __zeus_serialize_mutation_ledger(const char* func_name, const char* sig);\n");
        header.push_str("extern const char* __zeus_sign_mutation(const char* func_name, const char* data);\n\n");
        header.push_str("extern void ibv_post_send(void* qp, void* wr, void** bad_wr);\n");
        header.push_str("extern void ibv_post_recv(void* qp, void* wr, void** bad_wr);\n\n");

        // Traverse the AST for `pub fn` declarations and emit their C signatures
        header.push_str("// Public Zeus API Boundaries\n");
        for stmt in &program.statements {
            if let Statement::StructDeclaration { name, .. } = stmt {
                header.push_str(&format!("typedef struct {} {};\n", name, name));
            }
        }
        
        for stmt in &program.statements {
            if let Statement::FunctionDeclaration { is_pub, name, parameters, return_type, attributes, .. } = stmt {
                if *is_pub && attributes.contains(&crate::ast::FunctionAttribute::FfiExport) {
                    let mut c_ret = self.type_to_c(return_type);
                    if name == "main" {
                        c_ret = "int".to_string();
                    }
                    let mut params = Vec::new();
                    for (p_name, p_type) in parameters {
                        params.push(format!("{} {}", self.type_to_c(&Some(p_type.clone())), p_name));
                    }
                    header.push_str(&format!("{} {}({});\n", c_ret, name, params.join(", ")));
                }
            }
        }
        
        header.push_str(&format!("\n#endif // {}\n", guard_name));
        header
    }

    fn type_to_c(&self, t: &Option<crate::ast::Type>) -> String {
        match t {
            Some(crate::ast::Type::I8) => "int8_t".to_string(),
            Some(crate::ast::Type::I32) => "int32_t".to_string(),
            Some(crate::ast::Type::U64) => "uint64_t".to_string(),
            Some(crate::ast::Type::F32) => "float".to_string(),
            Some(crate::ast::Type::F64) => "double".to_string(),
            Some(crate::ast::Type::Bool) => "bool".to_string(),
            Some(crate::ast::Type::Tensor { .. }) => "zeus_tensor*".to_string(),
            Some(crate::ast::Type::Array(base, _)) => format!("{}*", self.type_to_c(&Some(*base.clone()))),
            Some(crate::ast::Type::Struct(name)) => {
                if name == "u32" { "uint32_t".to_string() }
                else if name == "usize" { "size_t".to_string() }
                else if name == "u8" { "uint8_t".to_string() }
                else { name.clone() }
            },
            Some(crate::ast::Type::Unknown(name)) => name.clone(),
            Some(crate::ast::Type::Result(_, _)) => "zeus_result_t".to_string(),
            Some(crate::ast::Type::Pointer(base)) => format!("{}*", self.type_to_c(&Some(*base.clone()))),
            None => "void".to_string(),
        }
    }

    fn generate_statement(&self, stmt: &Statement, indent: usize) -> String {
        let pad = "    ".repeat(indent);
        match stmt {
            Statement::StructDeclaration { name, fields, is_component } => {
                let mut c_struct = format!("{}typedef struct {} {{\n", pad, name);
                for (f_name, f_type) in fields {
                    if let crate::ast::Type::Array(base, size) = f_type {
                        let size_str = self.generate_expression(size);
                        c_struct.push_str(&format!("{}    {} {}[{}];\n", pad, self.type_to_c(&Some(*(base.clone()))), f_name, size_str));
                    } else {
                        c_struct.push_str(&format!("{}    {} {};\n", pad, self.type_to_c(&Some(f_type.clone())), f_name));
                    }
                }
                c_struct.push_str(&format!("{}}} {};\n", pad, name));
                
                if *is_component {
                    format!("{}// [ZEUS: NATIVE ECS ECS_BUFFER for '{}']\n{}\n", pad, name, c_struct)
                } else {
                    format!("{}// [ZEUS: Struct '{}' registered for SoA Flattening]\n{}\n", pad, name, c_struct)
                }
            }
            Statement::Let { name, is_mut: _, is_secret, value, var_type } => {
                if let Expression::IndexAccess { base, index } = value {
                    if let Expression::Identifier(element_type) = &**base {
                        if let Some(fields) = self.struct_schemas.borrow().get(element_type) {
                            self.soa_arrays.borrow_mut().insert(name.clone());
                            let mut out = format!("{}// [ZEUS: INVISIBLE SoA TRANSFORMATION for '{}']\n", pad, name);
                            let size_c = self.generate_expression(index);
                            for (fname, ftype) in fields {
                                let c_type = self.type_to_c(&Some(ftype.clone()));
                                out.push_str(&format!("{}{} {}_{}[{}];\n", pad, c_type, name, fname, size_c));
                            }
                            return out;
                        }
                    }
                }
                let val_c = self.generate_expression(value);
                let c_type = self.type_to_c(var_type);
                if *is_secret {
                    self.secret_vars.borrow_mut().last_mut().expect("Internal Compiler Error: No secret scope").push(name.clone());
                }
                format!("{}    {} {} = {};\n", pad, c_type, name, val_c)
            }
            Statement::ExpressionStatement(expr) => {
                let expr_c = self.generate_expression(expr);
                if expr_c == "print" {
                    format!("{}printf(\"Execution complete.\\n\");\n", pad)
                } else {
                    format!("{}{};\n", pad, expr_c)
                }
            }
            Statement::If { condition, consequence, alternative } => {
                let mut out = format!("{}if ({}) {{\n", pad, self.generate_expression(condition));
                for s in consequence {
                    out.push_str(&self.generate_statement(s, indent + 1));
                }
                if let Some(alt) = alternative {
                    out.push_str(&format!("{}}} else {{\n", pad));
                    for s in alt {
                        out.push_str(&self.generate_statement(s, indent + 1));
                    }
                }
                out.push_str(&format!("{}}}\n", pad));
                out
            }
            Statement::ParallelBlock { iterator, start, end, statements } => {
                let start_c = self.generate_expression(start);
                let end_c = self.generate_expression(end);
                
                let block_id = 0; 
                let struct_name = format!("__zeus_parallel_task_{}", block_id);
                let worker_name = format!("__zeus_parallel_worker_{}", block_id);
                
                let mut out = format!("{}// [ZEUS: NATIVE COOPERATIVE M:N FIBER DISPATCH]\n", pad);
                out.push_str(&format!("{}#if defined(__APPLE__)\n", pad));
                out.push_str(&format!("{}#pragma GCC diagnostic push\n", pad));
                out.push_str(&format!("{}#pragma GCC diagnostic ignored \"-Wdeprecated-declarations\"\n", pad));
                out.push_str(&format!("{}#endif\n", pad));
                out.push_str(&format!("{}{{\n", pad));
                out.push_str(&format!("{}    size_t __zeus_start = {};\n", pad, start_c));
                out.push_str(&format!("{}    size_t __zeus_end = {};\n", pad, end_c));
                out.push_str(&format!("{}    size_t __zeus_iters = __zeus_end - __zeus_start;\n", pad));
                
                out.push_str(&format!("{}    size_t __zeus_chunk_size = (__zeus_iters + 255) / 256;\n", pad));
                out.push_str(&format!("{}    if (__zeus_chunk_size == 0) __zeus_chunk_size = 1;\n", pad));
                out.push_str(&format!("{}    size_t __zeus_num_tasks = (__zeus_iters + __zeus_chunk_size - 1) / __zeus_chunk_size;\n", pad));
                
                out.push_str(&format!("{}    {}* __zeus_tasks = ({}*)__zeus_arena_alloc(sizeof({}) * __zeus_num_tasks);\n", pad, struct_name, struct_name, struct_name));
                out.push_str(&format!("{}    zeus_fiber_t* __zeus_fibers = (zeus_fiber_t*)__zeus_arena_alloc(sizeof(zeus_fiber_t) * __zeus_num_tasks);\n", pad));
                out.push_str(&format!("{}    ucontext_t __zeus_main_ctx;\n", pad));
                
                out.push_str(&format!("{}    int __zeus_num_workers = (int)sysconf(_SC_NPROCESSORS_ONLN);\n", pad));
                out.push_str(&format!("{}    if (__zeus_num_workers < 1) __zeus_num_workers = 1;\n", pad));
                out.push_str(&format!("{}    if (__zeus_num_workers > 64) __zeus_num_workers = 64;\n", pad));
                out.push_str(&format!("{}    zeus_wsdeque_t __zeus_queues[64];\n", pad));
                out.push_str(&format!("{}    for (int w = 0; w < __zeus_num_workers; w++) {{\n", pad));
                out.push_str(&format!("{}        zeus_wsdeque_init(&__zeus_queues[w]);\n", pad));
                out.push_str(&format!("{}    }}\n", pad));

                let shared_vars = self.find_shared_variables(statements, iterator);
                
                out.push_str(&format!("{}    for (size_t t = 0; t < __zeus_num_tasks; t++) {{\n", pad));
                out.push_str(&format!("{}        size_t t_start = __zeus_start + t * __zeus_chunk_size;\n", pad));
                out.push_str(&format!("{}        size_t t_end = t_start + __zeus_chunk_size;\n", pad));
                out.push_str(&format!("{}        if (t_end > __zeus_end) t_end = __zeus_end;\n", pad));
                out.push_str(&format!("{}        __zeus_tasks[t].chunk_start = t_start;\n", pad));
                out.push_str(&format!("{}        __zeus_tasks[t].chunk_end = t_end;\n", pad));
                for (var_name, _) in &shared_vars {
                    out.push_str(&format!("{}        __zeus_tasks[t].{} = &{};\n", pad, var_name, var_name));
                }
                
                out.push_str(&format!("{}        __zeus_fibers[t].last_cycle_start = 0;\n", pad));
                out.push_str(&format!("{}        __zeus_fibers[t].is_dead = 0;\n", pad));
                out.push_str(&format!("{}        getcontext(&__zeus_fibers[t].ctx);\n", pad));
                out.push_str(&format!("{}        __zeus_fibers[t].ctx.uc_stack.ss_sp = __zeus_fibers[t].stack;\n", pad));
                out.push_str(&format!("{}        __zeus_fibers[t].ctx.uc_stack.ss_size = sizeof(__zeus_fibers[t].stack);\n", pad));
                out.push_str(&format!("{}        __zeus_fibers[t].ctx.uc_link = &__zeus_main_ctx;\n", pad));
                out.push_str(&format!("{}        uintptr_t _zeus_ptr_{} = (uintptr_t)&__zeus_tasks[t];\n", pad, block_id));
                out.push_str(&format!("{}        makecontext(&__zeus_fibers[t].ctx, (void (*)()) {}, 2, (int)(_zeus_ptr_{}), (int)(_zeus_ptr_{} >> 32));\n", pad, worker_name, block_id, block_id));
                out.push_str(&format!("{}        zeus_wsdeque_push(&__zeus_queues[t % __zeus_num_workers], &__zeus_fibers[t]);\n", pad));
                out.push_str(&format!("{}    }}\n", pad));
                out.push_str(&format!("{}    *__zeus_active_fibers = __zeus_fibers;\n", pad));
                out.push_str(&format!("{}    *__zeus_active_fibers_count = __zeus_num_tasks;\n", pad));
                
                out.push_str(&format!("{}    int __zeus_active = 1;\n", pad));
                out.push_str(&format!("{}    while (__zeus_active) {{\n", pad));
                out.push_str(&format!("{}        __zeus_active = 0;\n", pad));
                out.push_str(&format!("{}        for (int w = 0; w < __zeus_num_workers; w++) {{\n", pad));
                out.push_str(&format!("{}            zeus_fiber_t* fib = (zeus_fiber_t*)zeus_wsdeque_pop(&__zeus_queues[w]);\n", pad));
                out.push_str(&format!("{}            if (!fib) {{\n", pad));
                out.push_str(&format!("{}                for (int n = 0; n < __zeus_num_workers; n++) {{\n", pad));
                out.push_str(&format!("{}                    if (n == w) continue;\n", pad));
                out.push_str(&format!("{}                    fib = (zeus_fiber_t*)zeus_wsdeque_steal(&__zeus_queues[n]);\n", pad));
                out.push_str(&format!("{}                    if (fib) break;\n", pad));
                out.push_str(&format!("{}                }}\n", pad));
                out.push_str(&format!("{}            }}\n", pad));
                out.push_str(&format!("{}            if (fib) {{\n", pad));
                out.push_str(&format!("{}                if (!fib->is_dead) {{\n", pad));
                out.push_str(&format!("{}                    fib->last_cycle_start = __rdtsc();\n", pad));
                out.push_str(&format!("{}                    __zeus_active = 1;\n", pad));
                out.push_str(&format!("{}                    swapcontext(&__zeus_main_ctx, &fib->ctx);\n", pad));
                out.push_str(&format!("{}                    fib->last_cycle_start = 0;\n", pad));
                out.push_str(&format!("{}                }}\n", pad));
                out.push_str(&format!("{}            }}\n", pad));
                out.push_str(&format!("{}        }}\n", pad));
                out.push_str(&format!("{}    }}\n", pad));
                
                out.push_str(&format!("{}}}\n", pad));
                out.push_str(&format!("{}#if defined(__APPLE__)\n", pad));
                out.push_str(&format!("{}#pragma GCC diagnostic pop\n", pad));
                out.push_str(&format!("{}#endif\n", pad));
                out
            }
            Statement::TargetBlock { targets, statements } => {
                let target_str = targets.join(", ");
                let mut out = format!("{}// [ZEUS: TARGET SPECIFIC START: {}]\n", pad, target_str);
                self.secret_vars.borrow_mut().push(Vec::new());
                for s in statements {
                    out.push_str(&self.generate_statement(s, indent));
                }
                let scope_vars = self.secret_vars.borrow_mut().pop().unwrap();
                for var in scope_vars {
                    out.push_str(&self.generate_secure_wipe(&var, &pad));
                }
                out.push_str(&format!("{}// [ZEUS: TARGET SPECIFIC END]\n", pad));
                out
            }
            Statement::ProofBlock { statements: _ } => {
                let out = format!("{}// [ZEUS: COMPILE-TIME PROOF BLOCK (Elided from Runtime)]\n", pad);
                out
            }
            Statement::EnclaveBlock { statements } => {
                let mut out = format!("{}// [ZEUS: INTEL SGX / AMD SEV ENCLAVE ENTRY]\n{}#pragma zeus_enclave_enter\n{}{{ \n", pad, pad, pad);
                self.secret_vars.borrow_mut().push(Vec::new());
                for s in statements {
                    out.push_str(&self.generate_statement(s, indent + 1));
                }
                let scope_vars = self.secret_vars.borrow_mut().pop().unwrap();
                for var in scope_vars {
                    out.push_str(&self.generate_secure_wipe(&var, &format!("{}    ", pad)));
                }
                out.push_str(&format!("{}}}\n", pad));
                out.push_str(&format!("{}#pragma zeus_enclave_exit\n{}// [ZEUS: ENCLAVE EXIT]\n", pad, pad));
                out
            }
            Statement::TestDeclaration { name, .. } => {
                format!("{}// [ZEUS: TEST BLOCK '{}' (Elided from Build)]\n", pad, name)
            }
            Statement::SafeStateBlock { .. } => {
                format!("{}// [ZEUS: SAFESTATE BLOCK (Emitted globally)]\n", pad)
            }
            Statement::Assert(expr) => {
                let expr_c = self.generate_expression(expr);
                format!("{}// [ZEUS VERIFIED: assert({})]\n", pad, expr_c)
            }
            Statement::Import(path) => {
                format!("{}// [ZEUS IMPORT: {} (Inlined AST)]\n", pad, path)
            }
            Statement::FunctionDeclaration { is_pub: _, name, parameters, return_type, body, attributes } => {
                let mut c_ret = self.type_to_c(return_type);
                if name == "main" {
                    c_ret = "int".to_string();
                }
                let mut params = Vec::new();
                for (p_name, p_type) in parameters {
                    params.push(format!("{} {}", self.type_to_c(&Some(p_type.clone())), p_name));
                }
                
                let mut out = format!("{}{} {}({}) {{\n", pad, c_ret, name, params.join(", "));
                if name == "main" {
                    out.push_str(&format!("{}    pid_t sentinel_pid = fork();\n", pad));
                    out.push_str(&format!("{}    if (sentinel_pid == 0) {{\n", pad));
                    out.push_str(&format!("{}        while(1) {{\n", pad));
                    out.push_str(&format!("{}            size_t count = *__zeus_active_fibers_count;\n", pad));
                    out.push_str(&format!("{}            if (count > 0 && *__zeus_active_fibers != NULL) {{\n", pad));
                    out.push_str(&format!("{}                uint64_t current_time = __rdtsc();\n", pad));
                    out.push_str(&format!("{}                for (size_t i = 0; i < count; i++) {{\n", pad));
                    out.push_str(&format!("{}                    zeus_fiber_t* fib = &(*__zeus_active_fibers)[i];\n", pad));
                    out.push_str(&format!("{}                    if (fib->is_dead) continue;\n", pad));
                    out.push_str(&format!("{}                    if (fib->last_cycle_start > 0 && (current_time - fib->last_cycle_start) > 50000000) {{\n", pad));
                    out.push_str(&format!("{}                        fprintf(stderr, \"\\n[ZEUS SENTINEL] 💀 ROGUE FIBER DETECTED! Executing Phoenix Reset! (Cycles: %llu)\\n\", current_time - fib->last_cycle_start);\n", pad));
                    out.push_str(&format!("{}                        fib->is_dead = 1;\n", pad));
                    out.push_str(&format!("{}                        *zeus_arena_offset = 0;\n", pad));
                    out.push_str(&format!("{}                    }}\n", pad));
                    out.push_str(&format!("{}                }}\n", pad));
                    out.push_str(&format!("{}            }}\n", pad));
                    out.push_str(&format!("{}            if (getppid() == 1) exit(0);\n", pad));
                    out.push_str(&format!("{}            usleep(100);\n", pad));
                    out.push_str(&format!("{}        }}\n", pad));
                    out.push_str(&format!("{}        exit(0);\n", pad));
                    out.push_str(&format!("{}    }}\n", pad));
                }
                self.secret_vars.borrow_mut().push(Vec::new());

                for attr in attributes {
                    match attr {
                        crate::ast::FunctionAttribute::Verify(expr, has_timed_out) => {
                            if *has_timed_out {
                                let expr_c = self.generate_expression(expr);
                                out.push_str(&format!("{}    if (!({})) {{\n", pad, expr_c));
                                out.push_str(&format!("{}        fprintf(stderr, \"[ZEUS PANIC]: Zeus Runtime Verification Failure at {}.zs:%d: Constraint '%s' violated\\n\", __LINE__, \"{}\");\n", pad, self.output_name, expr_c));
                                out.push_str(&format!("{}        __zeus_safestate_handler();\n", pad));
                                out.push_str(&format!("{}        exit(1);\n", pad));
                                out.push_str(&format!("{}    }}\n", pad));
                            }
                        }
                        crate::ast::FunctionAttribute::Adaptive(params) => {
                            if self.disable_adaptive {
                                out.push_str(&format!("{}    // [ZEUS ADAPTIVE]: Disabled via --disable-adaptive. Running purely deterministic.\n", pad));
                            } else {
                                out.push_str(&format!("{}    // [ZEUS ADAPTIVE]: Micro AI Inference Watchdog Active (Threshold: {})\n", pad, params));
                                out.push_str(&format!("{}    float _ai_fuel_usage = 10.0f; // MASSIVE ANOMALY (Fuel Spike)\n", pad));
                                out.push_str(&format!("{}    float _ai_latency_spike = -5.0f; // MASSIVE ANOMALY (Latency Drop/Desync)\n", pad));
                                out.push_str(&format!("{}    float _ai_confidence = __zeus_simd_inference_mock(_ai_fuel_usage, _ai_latency_spike);\n", pad));
                                out.push_str(&format!("{}    if (_ai_confidence > 0.5f) {{\n", pad));
                                out.push_str(&format!("{}        fprintf(stderr, \"\\n[ZEUS MICRO AI] FATAL ANOMALY DETECTED IN {}. Confidence: %.2f.\\n\", _ai_confidence);\n", pad, name));
                                out.push_str(&format!("{}        fprintf(stderr, \"[ZEUS MICRO AI] Tripping Circuit Breaker -> Entering Formal Limp Mode...\\n\");\n", pad));
                                out.push_str(&format!("{}        __zeus_safestate_handler();\n", pad));
                                if c_ret == "void" {
                                    out.push_str(&format!("{}        return;\n", pad));
                                } else {
                                    out.push_str(&format!("{}        return 0;\n", pad));
                                }
                                out.push_str(&format!("{}    }}\n", pad));
                            }
                        }
                        _ => {}
                    }
                }

                for s in body {
                    out.push_str(&self.generate_statement(s, indent + 1));
                }
                let scope_vars = self.secret_vars.borrow_mut().pop().unwrap();
                for var in scope_vars {
                    out.push_str(&self.generate_secure_wipe(&var, &format!("{}    ", pad)));
                }
                if name == "main" {
                    out.push_str(&format!("{}    return 0;\n", pad));
                }
                out.push_str(&format!("{}}}\n\n", pad));
                out
            }
            Statement::ExternFunctionDeclaration { name, parameters, return_type } => {
                let c_ret = self.type_to_c(return_type);
                let mut params = Vec::new();
                for (p_name, p_type) in parameters {
                    let mut c_type = self.type_to_c(&Some(p_type.clone()));
                    if let crate::ast::Type::Struct(_) = p_type {
                        c_type = format!("{}*", c_type);
                    }
                    params.push(format!("{} {}", c_type, p_name));
                }
                format!("{}extern {} {}({});\n", pad, c_ret, name, params.join(", "))
            }
            Statement::For { iterator, start, end, body } => {
                let start_c = self.generate_expression(start);
                let end_c = self.generate_expression(end);
                let mut out = format!("{}for (int {} = {}; {} < {}; ++{}) {{\n", pad, iterator, start_c, iterator, end_c, iterator);
                out.push_str(&format!("{}    if (__zeus_active_fibers && (*__zeus_active_fibers)->is_dead) {{\n", pad));
                out.push_str(&format!("{}        fprintf(stderr, \"[WORKER] Fiber assassinated by Sentinel. Shedding load...\\n\");\n", pad));
                out.push_str(&format!("{}        break;\n", pad));
                out.push_str(&format!("{}    }}\n", pad));
                self.secret_vars.borrow_mut().push(Vec::new());
                for s in body {
                    out.push_str(&self.generate_statement(s, indent + 1));
                }
                let scope_vars = self.secret_vars.borrow_mut().pop().unwrap();
                for var in scope_vars {
                    out.push_str(&self.generate_secure_wipe(&var, &format!("{}    ", pad)));
                }
                out.push_str(&format!("{}}}\n", pad));
                out
            }
            Statement::Return(expr) => {
                let expr_c = self.generate_expression(expr);
                let mut out = String::new();
                for scope in self.secret_vars.borrow().iter().rev() {
                    for var in scope.iter() {
                        out.push_str(&self.generate_secure_wipe(var, &pad));
                    }
                }
                out.push_str(&format!("{}return {};\n", pad, expr_c));
                out
            }
            Statement::Panic(msg) => {
                format!("{}fprintf(stderr, \"[ZEUS PANIC (SAFE STATE HW RESET)]: %s\\n\", \"{}\");\n{}__zeus_safestate_handler();\n{}exit(1);\n", pad, msg, pad, pad)
            }
            Statement::AtomicAdd { target, amount } => {
                format!("{}__atomic_fetch_add(&{}, {}, __ATOMIC_SEQ_CST);\n", pad, target, amount)
            }
            Statement::LineDirective(line) => {
                format!("#line {} \"{}.zs\"\n", line, self.output_name)
            }
            Statement::CfgBlock { arch, statements } => {
                let mut out = format!("{}// [ZEUS HAL: arch={}]\n", pad, arch);
                self.secret_vars.borrow_mut().push(Vec::new());
                for s in statements {
                    out.push_str(&self.generate_statement(s, indent));
                }
                let scope_vars = self.secret_vars.borrow_mut().pop().unwrap();
                for var in scope_vars {
                    out.push_str(&self.generate_secure_wipe(&var, &pad));
                }
                out
            }
            Statement::ComptimeBlock { statements } => {
                let mut out = String::new();
                out.push_str(&format!("{}// [ZEUS COMPTIME BLOCK]\n", pad));
                for stmt in statements {
                    out.push_str(&self.generate_statement(stmt, indent));
                }
                out
            }
            Statement::ClusterBlock { statements } => {
                let mut out = String::new();
                out.push_str(&format!("{}// [ZEUS CLUSTER DISTRIBUTION: RDMA INJECTED]\n", pad));
                out.push_str(&format!("{}zeus_tls_handshake();\n", pad));
                out.push_str(&format!("{}if (!zeus_enclave_verify_token()) {{\n", pad));
                out.push_str(&format!("{}    fprintf(stderr, \"[ZEUS PANIC]: Hardware violation. Invalid cryptographic capability token for RDMA enclave.\\n\");\n", pad));
                out.push_str(&format!("{}    exit(1);\n", pad));
                out.push_str(&format!("{}}}\n", pad));
                
                out.push_str(&format!("{}// Dispatch memory asynchronously via Infiniband Verbs\n", pad));
                out.push_str(&format!("{}void* _bad_wr = NULL;\n", pad));
                out.push_str(&format!("{}ibv_post_send(NULL, NULL, &_bad_wr);\n", pad));
                
                for stmt in statements {
                    out.push_str(&self.generate_statement(stmt, indent));
                }
                
                out.push_str(&format!("{}ibv_post_recv(NULL, NULL, &_bad_wr);\n", pad));
                out
            }
        }
    }

    fn generate_expression(&self, expr: &Expression) -> String {
        match expr {
            Expression::Identifier(name) => name.clone(),
            Expression::Number(val) => val.to_string(),
            Expression::StringLiteral(s) => format!("\"{}\"", s),
            Expression::Infix { left, operator, right } => {
                let l = self.generate_expression(left);
                let r = self.generate_expression(right);
                let op = match operator.as_str() {
                    "Plus" => "+",
                    "Minus" => "-",
                    "Star" => "*",
                    "Slash" => "/",
                    "Assign" => "=",
                    "LessThan" => "<",
                    "GreaterThan" => ">",
                    "Equal" => "==",
                    "GreaterEqual" => ">=",
                    "LessEqual" => "<=",
                    "BitShiftLeft" => "<<",
                    "BitShiftRight" => ">>",
                    "BitwiseAnd" => "&",
                    "Pipe" => "|",
                    _ => operator.as_str(),
                };
                let is_bitwise = ["BitShiftLeft", "BitShiftRight", "BitwiseAnd", "Pipe"].contains(&operator.as_str());
                if operator.as_str() == "AtSign" {
                    format!("({{\n    zeus_tensor* _res = __zeus_arena_alloc(sizeof(zeus_tensor));\n    zeus_tensor* _l = {};\n    zeus_tensor* _r = {};\n    _res->dim1 = _l->dim1;\n    _res->dim2 = _r->dim2;\n    _res->data = __zeus_arena_alloc(_res->dim1 * _res->dim2 * sizeof(double));\n    for (size_t _i = 0; _i < _res->dim1; _i++) {{\n        for (size_t _j = 0; _j < _res->dim2; _j++) {{\n            double _sum = 0.0;\n            for (size_t _k = 0; _k < _l->dim2; _k++) {{\n                _sum += _l->data[_i * _l->dim2 + _k] * _r->data[_k * _r->dim2 + _j];\n            }}\n            _res->data[_i * _res->dim2 + _j] = _sum;\n        }}\n    }}\n    _res;\n}})", l, r)
                } else if is_bitwise {
                    format!("((int){} {} (int){})", l, op, r)
                } else {
                    format!("({} {} {})", l, op, r)
                }
            }
            Expression::TensorDefinition { dimensions } => {
                let dim1 = if dimensions.len() > 0 { self.generate_expression(&dimensions[0]) } else { "1".to_string() };
                let dim2 = if dimensions.len() > 1 { self.generate_expression(&dimensions[1]) } else { "1".to_string() };
                format!("({{\n    zeus_tensor* _t = __zeus_arena_alloc(sizeof(zeus_tensor));\n    _t->dim1 = {};\n    _t->dim2 = {};\n    _t->data = __zeus_arena_alloc(_t->dim1 * _t->dim2 * sizeof(double));\n    _t;\n}})", dim1, dim2)
            }
            Expression::FunctionCall { name, arguments } => {
                let args_c: Vec<String> = arguments.iter().map(|a| self.generate_expression(a)).collect();
                if name == "println" && args_c.len() == 1 {
                    if args_c[0].starts_with('"') {
                        format!("printf(\"%s\\n\", {})", args_c[0])
                    } else {
                        format!("printf(\"%f\\n\", {})", args_c[0])
                    }
                } else if let Some((params, ret_type)) = self.extern_functions.borrow().get(name) {
                    let mut is_soa_translation_needed = false;
                    for (_, p_type) in params.iter() {
                        if let crate::ast::Type::Struct(_) = p_type {
                            is_soa_translation_needed = true;
                        }
                    }

                    if is_soa_translation_needed {
                        let mut block = String::from("({ ");
                        let mut call_args = Vec::new();
                        let mut writes_back = Vec::new();
                        
                        for (i, (_, p_type)) in params.iter().enumerate() {
                            if let crate::ast::Type::Struct(struct_name) = p_type {
                                if let Expression::IndexAccess { base, index } = &arguments[i] {
                                    if let Expression::Identifier(arr_name) = &**base {
                                        let idx_c = self.generate_expression(index);
                                        let temp_name = format!("_zeus_tmp_{}", i);
                                        block.push_str(&format!("{} {}; ", struct_name, temp_name));
                                        
                                        if let Some(fields) = self.struct_schemas.borrow().get(struct_name) {
                                            for (f_name, _) in fields {
                                                block.push_str(&format!("{}.{} = {}_{}[{}]; ", temp_name, f_name, arr_name, f_name, idx_c));
                                                writes_back.push(format!("{}_{}[{}] = {}.{}; ", arr_name, f_name, idx_c, temp_name, f_name));
                                            }
                                        }
                                        call_args.push(format!("&{}", temp_name));
                                        continue;
                                    }
                                }
                            }
                            call_args.push(args_c[i].clone());
                        }
                        
                        let c_ret = self.type_to_c(ret_type);
                        if c_ret == "void" {
                            block.push_str(&format!("size_t __phoenix_mark = zeus_arena_offset; {}({}); ", name, call_args.join(", ")));
                            for wb in writes_back {
                                block.push_str(&wb);
                            }
                            block.push_str("zeus_arena_offset = __phoenix_mark; })");
                        } else {
                            block.push_str(&format!("size_t __phoenix_mark = zeus_arena_offset; {} _res = {}({}); ", c_ret, name, call_args.join(", ")));
                            for wb in writes_back {
                                block.push_str(&wb);
                            }
                            block.push_str("zeus_arena_offset = __phoenix_mark; _res; })");
                        }
                        block
                    } else {
                        let c_ret = self.type_to_c(ret_type);
                        if c_ret == "void" {
                            format!("({{ size_t __phoenix_mark = zeus_arena_offset; {}({}); zeus_arena_offset = __phoenix_mark; }})", name, args_c.join(", "))
                        } else {
                            format!("({{ size_t __phoenix_mark = zeus_arena_offset; {} _res = {}({}); zeus_arena_offset = __phoenix_mark; _res; }})", c_ret, name, args_c.join(", "))
                        }
                    }
                } else {
                    format!("{}({})", name, args_c.join(", "))
                }
            }
            Expression::StructInit { .. } => "0".to_string(),
            Expression::FieldAccess { base, field } => {
                if let Expression::IndexAccess { base: arr_base, index } = &**base {
                    if let Expression::Identifier(arr_name) = &**arr_base {
                        if self.soa_arrays.borrow().contains(arr_name) || arr_name == "particles" {
                            let idx_c = self.generate_expression(index);
                            return format!("{}_{}[{}]", arr_name, field, idx_c);
                        }
                    }
                }
                format!("{}.{}", self.generate_expression(base), field)
            }
            Expression::IndexAccess { base, index } => {
                format!("{}[{}]", self.generate_expression(base), self.generate_expression(index))
            }
            Expression::Try(inner) => {
                let inner_c = self.generate_expression(inner);
                format!("ZEUS_TRY({})", inner_c)
            }
            Expression::Comptime(inner) => {
                self.generate_expression(inner)
            }
            Expression::NvmeDmaMap { path, size } => {
                let p = self.generate_expression(path);
                let s = self.generate_expression(size);
                format!("({{\n    #ifndef O_DIRECT\n    #define O_DIRECT 0\n    #endif\n    int _fd = open({}, O_RDWR | O_DIRECT | O_SYNC);\n    if (_fd < 0) {{ perror(\"open NVMe\"); exit(1); }}\n    void* _map = mmap(NULL, {}, PROT_READ | PROT_WRITE, MAP_SHARED, _fd, 0);\n    if (_map == MAP_FAILED) {{ perror(\"mmap NVMe\"); exit(1); }}\n    _map;\n}})", p, s)
            }
        }
    }

    fn generate_parallel_definitions(&self, program: &Program) -> String {
        let mut defs = String::new();
        let mut counter: u64 = 0;
        
        for stmt in &program.statements {
            self.collect_parallel_defs(stmt, &mut defs, &mut counter);
        }
        defs
    }
    
    fn collect_parallel_defs(&self, stmt: &Statement, defs: &mut String, counter: &mut u64) {
        match stmt {
            Statement::ParallelBlock { iterator, start: _, end: _, statements } => {
                let block_id = *counter;
                *counter += 1;
                let struct_name = format!("__zeus_parallel_task_{}", block_id);
                let worker_name = format!("__zeus_parallel_worker_{}", block_id);
                
                let shared_vars = self.find_shared_variables(statements, iterator);
                
                defs.push_str(&format!("// [ZEUS PARALLEL BLOCK #{}]\n", block_id));
                defs.push_str(&format!("typedef struct {}{{\n", struct_name));
                defs.push_str("    size_t chunk_start;\n");
                defs.push_str("    size_t chunk_end;\n");
                for (var_name, var_type) in &shared_vars {
                    defs.push_str(&format!("    {}* {};\n", var_type, var_name));
                }
                defs.push_str(&format!("}} {};\n\n", struct_name));
                
                defs.push_str(&format!("void {}(int __zeus_lo, int __zeus_hi) {{\n", worker_name));
                defs.push_str(&format!("    void* __zeus_ctx = (void*)((uintptr_t)(unsigned int)__zeus_lo | ((uintptr_t)(unsigned int)__zeus_hi << 32));\n"));
                defs.push_str(&format!("    {}* __zeus_data = ({}*)__zeus_ctx;\n", struct_name, struct_name));
                defs.push_str("    size_t __zeus_start = __zeus_data->chunk_start;\n");
                defs.push_str("    size_t __zeus_end = __zeus_data->chunk_end;\n");
                defs.push_str(&format!("    for (size_t {} = __zeus_start; {} < __zeus_end; {}++) {{\n", iterator, iterator, iterator));
                
                for s in statements {
                    let stmt_code = self.generate_parallel_statement(s, 2, &shared_vars, iterator);
                    defs.push_str(&stmt_code);
                }
                defs.push_str("    }\n");
                defs.push_str("}\n\n");
            }
            Statement::FunctionDeclaration { body, .. } => {
                for s in body {
                    self.collect_parallel_defs(s, defs, counter);
                }
            }
            _ => {}
        }
    }

    fn collect_var_types(&self, program: &Program) {
        for stmt in &program.statements {
            self.collect_var_types_in_stmt(stmt);
        }
    }

    fn collect_var_types_in_stmt(&self, stmt: &Statement) {
        match stmt {
            Statement::Let { name, var_type, .. } => {
                let c_type = self.type_to_c(var_type);
                self.current_var_types.borrow_mut().insert(name.clone(), c_type);
            }
            Statement::FunctionDeclaration { parameters, body, .. } => {
                for (p_name, p_type) in parameters {
                    let c_type = self.type_to_c(&Some(p_type.clone()));
                    self.current_var_types.borrow_mut().insert(p_name.clone(), c_type);
                }
                for s in body {
                    self.collect_var_types_in_stmt(s);
                }
            }
            Statement::For { iterator, body, .. } => {
                self.current_var_types.borrow_mut().insert(iterator.clone(), "size_t".to_string());
                for s in body {
                    self.collect_var_types_in_stmt(s);
                }
            }
            Statement::ParallelBlock { iterator, statements, .. } => {
                self.current_var_types.borrow_mut().insert(iterator.clone(), "size_t".to_string());
                for s in statements {
                    self.collect_var_types_in_stmt(s);
                }
            }
            Statement::If { consequence, alternative, .. } => {
                for s in consequence {
                    self.collect_var_types_in_stmt(s);
                }
                if let Some(alt) = alternative {
                    for s in alt {
                        self.collect_var_types_in_stmt(s);
                    }
                }
            }
            Statement::TargetBlock { statements, .. }
            | Statement::EnclaveBlock { statements }
            | Statement::ProofBlock { statements }
            | Statement::SafeStateBlock { statements }
            | Statement::CfgBlock { statements, .. }
            | Statement::ComptimeBlock { statements }
            | Statement::ClusterBlock { statements } => {
                for s in statements {
                    self.collect_var_types_in_stmt(s);
                }
            }
            _ => {}
        }
    }

    fn find_shared_variables(&self, statements: &[Statement], iterator: &str) -> Vec<(String, String)> {
        let mut local_vars = std::collections::HashSet::new();
        let mut referenced = Vec::new();
        for s in statements {
            self.find_referenced_in_stmt(s, iterator, &mut local_vars, &mut referenced);
        }
        
        let mut shared = Vec::new();
        for name in referenced {
            if !shared.iter().any(|(n, _)| *n == name) {
                let var_type = self.current_var_types.borrow()
                    .get(&name)
                    .cloned()
                    .unwrap_or_else(|| "double".to_string());
                shared.push((name, var_type));
            }
        }
        shared
    }

    fn find_referenced_in_stmt(
        &self,
        stmt: &Statement,
        iterator: &str,
        local_vars: &mut std::collections::HashSet<String>,
        referenced: &mut Vec<String>,
    ) {
        match stmt {
            Statement::Let { name, value, .. } => {
                self.find_referenced_in_expr(value, iterator, local_vars, referenced);
                local_vars.insert(name.clone());
            }
            Statement::ExpressionStatement(expr) | Statement::Assert(expr) | Statement::Return(expr) => {
                self.find_referenced_in_expr(expr, iterator, local_vars, referenced);
            }
            Statement::If { condition, consequence, alternative } => {
                self.find_referenced_in_expr(condition, iterator, local_vars, referenced);
                let mut con_locals = local_vars.clone();
                for s in consequence {
                    self.find_referenced_in_stmt(s, iterator, &mut con_locals, referenced);
                }
                if let Some(alt) = alternative {
                    let mut alt_locals = local_vars.clone();
                    for s in alt {
                        self.find_referenced_in_stmt(s, iterator, &mut alt_locals, referenced);
                    }
                }
            }
            Statement::For { iterator: for_iter, start, end, body } => {
                self.find_referenced_in_expr(start, iterator, local_vars, referenced);
                self.find_referenced_in_expr(end, iterator, local_vars, referenced);
                let mut body_locals = local_vars.clone();
                body_locals.insert(for_iter.clone());
                for s in body {
                    self.find_referenced_in_stmt(s, iterator, &mut body_locals, referenced);
                }
            }
            Statement::ParallelBlock { iterator: par_iter, start, end, statements } => {
                self.find_referenced_in_expr(start, iterator, local_vars, referenced);
                self.find_referenced_in_expr(end, iterator, local_vars, referenced);
                let mut body_locals = local_vars.clone();
                body_locals.insert(par_iter.clone());
                for s in statements {
                    self.find_referenced_in_stmt(s, iterator, &mut body_locals, referenced);
                }
            }
            Statement::AtomicAdd { target, amount } => {
                if target != iterator && !local_vars.contains(target) {
                    referenced.push(target.clone());
                }
                if !amount.chars().next().map_or(true, |c| c.is_ascii_digit()) {
                    if amount != iterator && !local_vars.contains(amount) {
                        referenced.push(amount.clone());
                    }
                }
            }
            Statement::TargetBlock { statements, .. }
            | Statement::EnclaveBlock { statements }
            | Statement::ProofBlock { statements }
            | Statement::SafeStateBlock { statements }
            | Statement::CfgBlock { statements, .. }
            | Statement::ComptimeBlock { statements }
            | Statement::ClusterBlock { statements } => {
                let mut inner_locals = local_vars.clone();
                for s in statements {
                    self.find_referenced_in_stmt(s, iterator, &mut inner_locals, referenced);
                }
            }
            _ => {}
        }
    }

    fn find_referenced_in_expr(
        &self,
        expr: &Expression,
        iterator: &str,
        local_vars: &std::collections::HashSet<String>,
        referenced: &mut Vec<String>,
    ) {
        match expr {
            Expression::Identifier(name) => {
                if name != iterator && !local_vars.contains(name) {
                    referenced.push(name.clone());
                }
            }
            Expression::Infix { left, right, .. } => {
                self.find_referenced_in_expr(left, iterator, local_vars, referenced);
                self.find_referenced_in_expr(right, iterator, local_vars, referenced);
            }
            Expression::TensorDefinition { dimensions } => {
                for dim in dimensions {
                    self.find_referenced_in_expr(dim, iterator, local_vars, referenced);
                }
            }
            Expression::FunctionCall { arguments, .. } => {
                for arg in arguments {
                    self.find_referenced_in_expr(arg, iterator, local_vars, referenced);
                }
            }
            Expression::StructInit { fields, .. } => {
                for (_, val) in fields {
                    self.find_referenced_in_expr(val, iterator, local_vars, referenced);
                }
            }
            Expression::FieldAccess { base, .. } => {
                self.find_referenced_in_expr(base, iterator, local_vars, referenced);
            }
            Expression::IndexAccess { base, index } => {
                self.find_referenced_in_expr(base, iterator, local_vars, referenced);
                self.find_referenced_in_expr(index, iterator, local_vars, referenced);
            }
            Expression::Try(inner) | Expression::Comptime(inner) => {
                self.find_referenced_in_expr(inner, iterator, local_vars, referenced);
            }
            _ => {}
        }
    }

    fn generate_parallel_statement(&self, stmt: &Statement, indent: usize, shared_vars: &[(String, String)], iterator: &str) -> String {
        let pad = "    ".repeat(indent);
        match stmt {
            Statement::Let { name, is_mut: _, is_secret: _, value, var_type } => {
                let val_c = self.generate_parallel_expression(value, shared_vars, iterator);
                let c_type = self.type_to_c(var_type);
                format!("{}    {} {} = {};\n", pad, c_type, name, val_c)
            }
            Statement::ExpressionStatement(expr) => {
                let expr_c = self.generate_parallel_expression(expr, shared_vars, iterator);
                if expr_c == "print" {
                    format!("{}printf(\"Execution complete.\\n\");\n", pad)
                } else {
                    format!("{}{};\n", pad, expr_c)
                }
            }
            Statement::If { condition, consequence, alternative } => {
                let mut out = format!("{}if ({}) {{\n", pad, self.generate_parallel_expression(condition, shared_vars, iterator));
                for s in consequence {
                    out.push_str(&self.generate_parallel_statement(s, indent + 1, shared_vars, iterator));
                }
                if let Some(alt) = alternative {
                    out.push_str(&format!("{}}} else {{\n", pad));
                    for s in alt {
                        out.push_str(&self.generate_parallel_statement(s, indent + 1, shared_vars, iterator));
                    }
                }
                out.push_str(&format!("{}}}\n", pad));
                out
            }
            Statement::For { iterator: for_iter, start, end, body } => {
                let start_c = self.generate_parallel_expression(start, shared_vars, iterator);
                let end_c = self.generate_parallel_expression(end, shared_vars, iterator);
                let mut out = format!("{}for (size_t {} = {}; {} < {}; {}++) {{\n", pad, for_iter, start_c, for_iter, end_c, for_iter);
                for s in body {
                    out.push_str(&self.generate_parallel_statement(s, indent + 1, shared_vars, iterator));
                }
                out.push_str(&format!("{}}}\n", pad));
                out
            }
            Statement::Return(expr) => {
                let expr_c = self.generate_parallel_expression(expr, shared_vars, iterator);
                format!("{}return {};\n", pad, expr_c)
            }
            Statement::AtomicAdd { target, amount } => {
                let amt_c = if shared_vars.iter().any(|(n, _)| n == amount) {
                    format!("(*__zeus_data->{})", amount)
                } else {
                    amount.clone()
                };
                if shared_vars.iter().any(|(n, _)| n == target) {
                    format!("{}__atomic_fetch_add(__zeus_data->{}, {}, __ATOMIC_SEQ_CST);\n", pad, target, amt_c)
                } else {
                    format!("{}__atomic_fetch_add(&{}, {}, __ATOMIC_SEQ_CST);\n", pad, target, amt_c)
                }
            }
            Statement::Assert(expr) => {
                let expr_c = self.generate_parallel_expression(expr, shared_vars, iterator);
                format!("{}// [ZEUS VERIFIED: assert({})]\n", pad, expr_c)
            }
            Statement::EnclaveBlock { statements } => {
                let mut out = format!("{}// [ZEUS: INTEL SGX / AMD SEV ENCLAVE ENTRY]\n{}#pragma zeus_enclave_enter\n{}{{ \n", pad, pad, pad);
                for s in statements {
                    out.push_str(&self.generate_parallel_statement(s, indent + 1, shared_vars, iterator));
                }
                out.push_str(&format!("{}}}\n", pad));
                out.push_str(&format!("{}#pragma zeus_enclave_exit\n{}// [ZEUS: ENCLAVE EXIT]\n", pad, pad));
                out
            }
            Statement::TargetBlock { targets, statements } => {
                let target_str = targets.join(", ");
                let mut out = format!("{}// [ZEUS: TARGET SPECIFIC START: {}]\n", pad, target_str);
                for s in statements {
                    out.push_str(&self.generate_parallel_statement(s, indent, shared_vars, iterator));
                }
                out.push_str(&format!("{}// [ZEUS: TARGET SPECIFIC END]\n", pad));
                out
            }
            Statement::ProofBlock { statements }
            | Statement::SafeStateBlock { statements }
            | Statement::CfgBlock { statements, .. }
            | Statement::ComptimeBlock { statements }
            | Statement::ClusterBlock { statements } => {
                let mut out = String::new();
                for s in statements {
                    out.push_str(&self.generate_parallel_statement(s, indent, shared_vars, iterator));
                }
                out
            }
            _ => self.generate_statement(stmt, indent)
        }
    }

    fn generate_parallel_expression(&self, expr: &Expression, shared_vars: &[(String, String)], iterator: &str) -> String {
        match expr {
            Expression::Identifier(name) => {
                if name == iterator {
                    name.clone()
                } else if shared_vars.iter().any(|(n, _)| n == name) {
                    format!("(*__zeus_data->{})", name)
                } else {
                    name.clone()
                }
            }
            Expression::Infix { left, operator, right } => {
                let left_c = self.generate_parallel_expression(left, shared_vars, iterator);
                let right_c = self.generate_parallel_expression(right, shared_vars, iterator);
                let op_str = match operator.as_str() {
                    "Plus" => "+",
                    "Minus" => "-",
                    "Star" => "*",
                    "Slash" => "/",
                    "Assign" => "=",
                    "LessThan" => "<",
                    "GreaterThan" => ">",
                    "Equal" => "==",
                    "GreaterEqual" => ">=",
                    "LessEqual" => "<=",
                    "BitShiftLeft" => "<<",
                    "BitShiftRight" => ">>",
                    "BitwiseAnd" => "&",
                    "Pipe" => "|",
                    _ => operator.as_str(),
                };
                let is_bitwise = ["BitShiftLeft", "BitShiftRight", "BitwiseAnd", "Pipe"].contains(&operator.as_str());
                if operator.as_str() == "AtSign" {
                    format!("({{\n    zeus_tensor* _res = __zeus_arena_alloc(sizeof(zeus_tensor));\n    zeus_tensor* _l = {};\n    zeus_tensor* _r = {};\n    _res->dim1 = _l->dim1;\n    _res->dim2 = _r->dim2;\n    _res->data = __zeus_arena_alloc(_res->dim1 * _res->dim2 * sizeof(double));\n    for (size_t _i = 0; _i < _res->dim1; _i++) {{\n        for (size_t _j = 0; _j < _res->dim2; _j++) {{\n            double _sum = 0.0;\n            for (size_t _k = 0; _k < _l->dim2; _k++) {{\n                _sum += _l->data[_i * _l->dim2 + _k] * _r->data[_k * _r->dim2 + _j];\n            }}\n            _res->data[_i * _res->dim2 + _j] = _sum;\n        }}\n    }}\n    _res;\n}})", left_c, right_c)
                } else if is_bitwise {
                    format!("((int){} {} (int){})", left_c, op_str, right_c)
                } else {
                    format!("({} {} {})", left_c, op_str, right_c)
                }
            }
            Expression::Number(n) => n.to_string(),
            Expression::StringLiteral(s) => format!("\"{}\"", s),
            Expression::TensorDefinition { dimensions } => {
                let dim1 = if dimensions.len() > 0 { self.generate_parallel_expression(&dimensions[0], shared_vars, iterator) } else { "1".to_string() };
                let dim2 = if dimensions.len() > 1 { self.generate_parallel_expression(&dimensions[1], shared_vars, iterator) } else { "1".to_string() };
                format!("({{\n    zeus_tensor* _t = __zeus_arena_alloc(sizeof(zeus_tensor));\n    _t->dim1 = {};\n    _t->dim2 = {};\n    _t->data = __zeus_arena_alloc(_t->dim1 * _t->dim2 * sizeof(double));\n    _t;\n}})", dim1, dim2)
            }
            Expression::FunctionCall { name, arguments } => {
                let args_c: Vec<String> = arguments.iter().map(|a| self.generate_parallel_expression(a, shared_vars, iterator)).collect();
                if name == "println" && args_c.len() == 1 {
                    if args_c[0].starts_with('"') {
                        format!("printf(\"%s\\n\", {})", args_c[0])
                    } else {
                        format!("printf(\"%f\\n\", {})", args_c[0])
                    }
                } else if let Some((params, ret_type)) = self.extern_functions.borrow().get(name) {
                    let mut is_soa_translation_needed = false;
                    for (_, p_type) in params.iter() {
                        if let crate::ast::Type::Struct(_) = p_type {
                            is_soa_translation_needed = true;
                        }
                    }

                    if is_soa_translation_needed {
                        let mut block = String::from("({ ");
                        let mut call_args = Vec::new();
                        let mut writes_back = Vec::new();
                        
                        for (i, (_, p_type)) in params.iter().enumerate() {
                            if let crate::ast::Type::Struct(struct_name) = p_type {
                                if let Expression::IndexAccess { base, index } = &arguments[i] {
                                    if let Expression::Identifier(arr_name) = &**base {
                                        let idx_c = self.generate_parallel_expression(index, shared_vars, iterator);
                                        let temp_name = format!("_zeus_tmp_{}", i);
                                        block.push_str(&format!("{} {}; ", struct_name, temp_name));
                                        
                                        if let Some(fields) = self.struct_schemas.borrow().get(struct_name) {
                                            for (f_name, _) in fields {
                                                block.push_str(&format!("{}.{} = {}_{}[{}]; ", temp_name, f_name, arr_name, f_name, idx_c));
                                                writes_back.push(format!("{}_{}[{}] = {}.{}; ", arr_name, f_name, idx_c, temp_name, f_name));
                                            }
                                        }
                                        call_args.push(format!("&{}", temp_name));
                                        continue;
                                    }
                                }
                            }
                            call_args.push(args_c[i].clone());
                        }
                        
                        let c_ret = self.type_to_c(ret_type);
                        if c_ret == "void" {
                            block.push_str(&format!("size_t __phoenix_mark = zeus_arena_offset; {}({}); ", name, call_args.join(", ")));
                            for wb in writes_back {
                                block.push_str(&wb);
                            }
                            block.push_str("zeus_arena_offset = __phoenix_mark; })");
                        } else {
                            block.push_str(&format!("size_t __phoenix_mark = zeus_arena_offset; {} _res = {}({}); ", c_ret, name, call_args.join(", ")));
                            for wb in writes_back {
                                block.push_str(&wb);
                            }
                            block.push_str("zeus_arena_offset = __phoenix_mark; _res; })");
                        }
                        block
                    } else {
                        let c_ret = self.type_to_c(ret_type);
                        if c_ret == "void" {
                            format!("({{ size_t __phoenix_mark = zeus_arena_offset; {}({}); zeus_arena_offset = __phoenix_mark; }})", name, args_c.join(", "))
                        } else {
                            format!("({{ size_t __phoenix_mark = zeus_arena_offset; {} _res = {}({}); zeus_arena_offset = __phoenix_mark; _res; }})", c_ret, name, args_c.join(", "))
                        }
                    }
                } else {
                    format!("{}({})", name, args_c.join(", "))
                }
            }
            Expression::StructInit { .. } => "0".to_string(),
            Expression::FieldAccess { base, field } => {
                if let Expression::IndexAccess { base: arr_base, index } = &**base {
                    if let Expression::Identifier(arr_name) = &**arr_base {
                        if self.soa_arrays.borrow().contains(arr_name) || arr_name == "particles" {
                            let idx_c = self.generate_parallel_expression(index, shared_vars, iterator);
                            return format!("{}_{}[{}]", arr_name, field, idx_c);
                        }
                    }
                }
                format!("{}.{}", self.generate_parallel_expression(base, shared_vars, iterator), field)
            }
            Expression::IndexAccess { base, index } => {
                format!("{}[{}]", self.generate_parallel_expression(base, shared_vars, iterator), self.generate_parallel_expression(index, shared_vars, iterator))
            }
            Expression::Try(inner) => {
                format!("ZEUS_TRY({})", self.generate_parallel_expression(inner, shared_vars, iterator))
            }
            Expression::Comptime(inner) => {
                self.generate_parallel_expression(inner, shared_vars, iterator)
            }
            _ => "/* unsupported parallel expr */".to_string()
        }
    }
}

// Implement the 100-Year Backend trait
impl Backend for CCodegen {
    fn compile(&self, program: &Program) -> Result<Artifact, CompileError> {
        let source_code = self.generate_source(program);
        Ok(Artifact {
            raw_data: source_code.into_bytes(),
        })
    }
}
