// Auto-generated by Zeus v0.1
#ifndef MAIN_H
#define MAIN_H

#include <stddef.h>

typedef struct {
    double* data;
    size_t dim1;
    size_t dim2;
} zeus_tensor;

void zeus_free_tensor(zeus_tensor* t);

// Public Zeus API Boundaries
double zeus_hw_read_sensor();
void main();

#endif // MAIN_H
