// Auto-generated by Zeus v0.1
#ifndef ADVANCED_INTEROP_H
#define ADVANCED_INTEROP_H

#include <stddef.h>

typedef struct {
    double* data;
    size_t dim1;
    size_t dim2;
} zeus_tensor;

void zeus_free_tensor(zeus_tensor* t);

// Public Zeus API Boundaries
double calculate_ai_load(zeus_tensor data, double iterations);

#endif // ADVANCED_INTEROP_H
