// Auto-generated by Zeus v0.1
#ifndef GREEN_TEST_H
#define GREEN_TEST_H

#include <stddef.h>

typedef struct {
    double* data;
    size_t dim1;
    size_t dim2;
} zeus_tensor;

void zeus_free_tensor(zeus_tensor* t);

// Public Zeus API Boundaries
double process_data();

#endif // GREEN_TEST_H
