// Auto-generated by Zeus v0.1
#ifndef IO_TEST_TEST_H
#define IO_TEST_TEST_H

#include <stddef.h>

typedef struct {
    double* data;
    size_t dim1;
    size_t dim2;
} zeus_tensor;

void zeus_free_tensor(zeus_tensor* t);

// Public Zeus API Boundaries
void main();

#endif // IO_TEST_TEST_H
