// Auto-generated by Zeus v0.1
#ifndef NATIVE_ENGINE_H
#define NATIVE_ENGINE_H

#include <stddef.h>
#include <stdint.h>

typedef struct {
    double* data;
    size_t dim1;
    size_t dim2;
} zeus_tensor;

void zeus_free_tensor(zeus_tensor* t);

typedef struct {
    int is_error;
    double ok_val;
    double err_val;
} zeus_result_t;

#define ZEUS_TRY(expr) ({ \
    zeus_result_t _res = (expr); \
    if (_res.is_error) return _res; \
    _res.ok_val; \
})

// Public Zeus API Boundaries
typedef struct DiagnosticPayload DiagnosticPayload;
uint32_t zeus_process_stream(DiagnosticPayload* payloads, size_t count);

#endif // NATIVE_ENGINE_H
