// Auto-generated by Zeus v0.1
#ifndef SAFETY_TEST_H
#define SAFETY_TEST_H

#include <stddef.h>

typedef struct {
    double* data;
    size_t dim1;
    size_t dim2;
} zeus_tensor;

void zeus_free_tensor(zeus_tensor* t);

// Public Zeus API Boundaries
void initialize_engine();

#endif // SAFETY_TEST_H
